;;;; test/snp/snp-verify.lisp -- SEV-SNP report verification in Lisp, end to end:
;;;;   ARK --RSA-PSS--> ASK --RSA-PSS--> VCEK (or VLEK)  --ECDSA P-384--> REPORT
;;;; Hosted CLI.  Usage (see test/snp/verify-chain-test.lisp for a driver):
;;;;   (snp-verify-report REPORT-BYTES ARK-DER ASK-DER VCEK-DER)  => T / NIL, printing each step.
;;;; Profile (checked, anything else is refused): RSA-PSS with SHA-384, MGF1-SHA-384,
;;;; salt 48, public exponent 65537 for ARK/ASK; ECDSA on secp384r1 with SHA-384 for the report.
;;;; Depends on: sha512 family in net/crypto.lisp (sha512-init, sha512-block), bignum integers.

;;; ---- bytes and integers ----
(defun %sv-int-be (v s e)
  (let ((n 0)) (do ((i s (+ i 1))) ((>= i e) n) (setq n (+ (* n 256) (aref v i))))))
(defun %sv-int-le (v s e)
  (let ((n 0)) (do ((i (- e 1) (- i 1))) ((< i s) n) (setq n (+ (* n 256) (aref v i))))))
(defun %sv-bytes-be (n len)
  (let ((v (make-array len :element-type '(unsigned-byte 8))) (x n))
    (do ((i (- len 1) (- i 1))) ((< i 0) v)
      (setf (aref v i) (mod x 256)) (setq x (floor x 256)))))
(defun %sv-cat (&rest vs)
  (let* ((n (reduce #'+ vs :key #'length))
         (out (make-array n :element-type '(unsigned-byte 8))) (k 0))
    (dolist (v vs out)
      (dotimes (i (length v)) (setf (aref out k) (aref v i)) (setq k (+ k 1))))))
(defun %sv-slice (v s e)
  (let ((out (make-array (- e s) :element-type '(unsigned-byte 8))))
    (dotimes (i (- e s) out) (setf (aref out i) (aref v (+ s i))))))
(defun %sv-same (a b)
  (and (= (length a) (length b))
       (let ((ok t)) (dotimes (i (length a) ok) (unless (= (aref a i) (aref b i)) (setq ok nil))))))
(defun %sv-xor (a b)
  (let ((out (make-array (length a) :element-type '(unsigned-byte 8))))
    (dotimes (i (length a) out) (setf (aref out i) (logxor (aref a i) (aref b i))))))

;;; ---- SHA-384 (SHA-512 with its own IV, truncated) ----
(defun %sv-sha384 (msg)
  (sha512-init)
  (let* ((msg-len (length msg))
         (full (* 128 (floor msg-len 128)))
         (rem (- msg-len full))
         (tlen (if (< rem 112) 128 256))
         (tail (make-array tlen :element-type '(unsigned-byte 8) :initial-element 0))
         (h (make-array 64 :element-type '(unsigned-byte 8)))
         (w (make-array 640)))
    (let ((iv (list #xcbbb9d5dc1059ed8 #x629a292a367cd507 #x9159015a3070dd17 #x152fecd8f70e5939
                    #x67332667ffc00b31 #x8eb44a8768581511 #xdb0c2e0d64f98fa7 #x47b5481dbefa4fa4)))
      (let ((i 0))
        (dolist (x iv)
          (dotimes (b 8) (setf (aref h (+ (* i 8) b)) (ldb (byte 8 (* 8 (- 7 b))) x)))
          (setq i (+ i 1)))))
    (let ((offset 0))
      (loop (when (not (< offset full)) (return ()))
            (sha512-block msg offset h w)
            (setq offset (+ offset 128))))
    (dotimes (i rem) (setf (aref tail i) (aref msg (+ full i))))
    (setf (aref tail rem) #x80)
    (let ((bits (* msg-len 8)) (hi (ash msg-len -29)))
      (dotimes (k 8)
        (setf (aref tail (- tlen 1 k)) (ldb (byte 8 (* 8 k)) bits))
        (setf (aref tail (- tlen 9 k)) (ldb (byte 8 (* 8 k)) hi))))
    (sha512-block tail 0 h w)
    (when (= tlen 256) (sha512-block tail 128 h w))
    (%sv-slice h 0 48)))

;;; ---- DER ----
(defun %sv-tlv (v pos)
  "(tag content-start content-end) for the element at POS."
  (let* ((tag (aref v pos)) (b (aref v (+ pos 1))) (cs 0) (len 0))
    (if (< b 128)
        (setq cs (+ pos 2) len b)
        (let ((nb (- b 128)))
          (setq len (%sv-int-be v (+ pos 2) (+ pos 2 nb)))
          (setq cs (+ pos 2 nb))))
    (list tag cs (+ cs len))))
(defun %sv-children (v s e)
  "List of (tag cs ce start) for the TLVs fully inside [s, e)."
  (let ((out nil) (pos s))
    (loop (when (>= pos e) (return (nreverse out)))
          (let ((x (%sv-tlv v pos)))
            (push (list (first x) (second x) (third x) pos) out)
            (setq pos (third x))))))
(defun %sv-oid-bytes (v tlv) (%sv-slice v (second tlv) (third tlv)))

;;; ---- certificates: (values tbs-bytes sig-alg-bytes sig-bytes spki-alg spki-key) ----
(defun %sv-parse-cert (der)
  (let* ((cert (%sv-tlv der 0))
         (kids (%sv-children der (second cert) (third cert)))
         (tbs-k (first kids)) (alg-k (second kids)) (sig-k (third kids))
         (tbs-bytes (%sv-slice der (fourth tbs-k) (third tbs-k)))
         (tbs-inner (%sv-children der (second tbs-k) (third tbs-k)))
         (has-version (= (first (first tbs-inner)) #xa0))
         (spki (nth (if has-version 6 5) tbs-inner))
         (spki-kids (%sv-children der (second spki) (third spki)))
         (spki-alg (first spki-kids))
         (spki-key-bits (second spki-kids))
         (sig-alg-bytes (%sv-slice der (fourth alg-k) (third alg-k)))
         (sig-bytes (%sv-slice der (+ (second sig-k) 1) (third sig-k)))
         (key-bytes (%sv-slice der (+ (second spki-key-bits) 1) (third spki-key-bits)))
         (alg-oid (%sv-oid-bytes der (first (%sv-children der (second spki-alg) (third spki-alg))))))
    (let* ((validity (nth (if has-version 4 3) tbs-inner))
           (vkids (%sv-children der (second validity) (third validity)))
           (not-before (%sv-time der (first vkids)))
           (not-after (%sv-time der (second vkids)))
           (ext-k (car (last tbs-inner)))
           (exts (if (= (first ext-k) #xa3) (%sv-extensions der ext-k) nil)))
      (list tbs-bytes sig-alg-bytes sig-bytes alg-oid key-bytes not-before not-after exts))))

;;; ---- validity: UTCTime (0x17) and GeneralizedTime (0x18) to Unix seconds ----
(defun %sv-days-from-civil (y m d)
  (let* ((y (if (<= m 2) (- y 1) y))
         (era (floor y 400))
         (yoe (- y (* era 400)))
         (doy (+ (floor (+ (* 153 (if (> m 2) (- m 3) (+ m 9))) 2) 5) (- d 1)))
         (doe (+ (* yoe 365) (floor yoe 4) (- (floor yoe 100)) doy)))
    (+ (* era 146097) doe -719468)))
(defun %sv-time (v tlv)
  "Unix seconds for a UTCTime or GeneralizedTime element."
  (let* ((tag (first tlv)) (s (second tlv))
         (txt (map 'string #'code-char (%sv-slice v s (third tlv))))
         (num (lambda (a b) (parse-integer txt :start a :end b)))
         (gen (= tag #x18))
         (year (if gen (funcall num 0 4)
                   (let ((yy (funcall num 0 2))) (if (< yy 50) (+ 2000 yy) (+ 1900 yy)))))
         (o (if gen 4 2)))
    (+ (* 86400 (%sv-days-from-civil year (funcall num o (+ o 2)) (funcall num (+ o 2) (+ o 4))))
       (* 3600 (funcall num (+ o 4) (+ o 6)))
       (* 60 (funcall num (+ o 6) (+ o 8)))
       (funcall num (+ o 8) (+ o 10)))))

;;; ---- extensions: alist of (oid-bytes . value-bytes), value = the OCTET STRING content ----
(defun %sv-extensions (v ext-k)
  (let* ((seqs (%sv-children v (second ext-k) (third ext-k)))
         (exts (%sv-children v (second (first seqs)) (third (first seqs))))
         (out nil))
    (dolist (e exts (nreverse out))
      (let* ((parts (%sv-children v (second e) (third e)))
             (oid (%sv-oid-bytes v (first parts)))
             (oct (car (last parts))))
        (push (cons oid (%sv-slice v (second oct) (third oct))) out)))))
(defun %sv-ext (exts oid-list)
  "The value of the extension whose OID is OID-LIST (a list of byte values), or NIL."
  (let ((want (coerce oid-list '(vector (unsigned-byte 8)))))
    (cdr (assoc-if (lambda (k) (%sv-same k want)) exts))))

(defun %sv-rsa-key (key-bytes)
  "The RSAPublicKey inside a BIT STRING payload: (n e)."
  (let* ((seq (%sv-tlv key-bytes 0))
         (ints (%sv-children key-bytes (second seq) (third seq)))
         (n (%sv-int-be key-bytes (second (first ints)) (third (first ints))))
         (e (%sv-int-be key-bytes (second (second ints)) (third (second ints)))))
    (list n e)))

;;; ---- RSA-PSS (RFC 8017 8.1.2), SHA-384 / MGF1-SHA-384 / salt 48 / e = 65537 ----
(defun %sv-modexp (base e n)
  (let ((r 1) (b (mod base n)) (x e))
    (loop (when (<= x 0) (return r))
          (when (oddp x) (setq r (mod (* r b) n)))
          (setq b (mod (* b b) n))
          (setq x (floor x 2)))))
(defun %sv-mgf1 (seed len)
  (let ((out nil) (count 0) (got 0))
    (loop (when (>= got len) (return))
          (let ((h (%sv-sha384 (%sv-cat seed (%sv-bytes-be count 4)))))
            (push h out) (setq got (+ got 48)) (setq count (+ count 1))))
    (%sv-slice (apply #'%sv-cat (nreverse out)) 0 len)))
(defun %sv-rsa-pss-verify (n e msg sig)
  "T when SIG is a valid RSASSA-PSS (SHA-384, MGF1-SHA-384, salt 48) signature of MSG under (n, e)."
  (let* ((s (%sv-int-be sig 0 (length sig)))
         (m (%sv-modexp s e n))
         (em-bits (- (integer-length n) 1))
         (em-len (ceiling em-bits 8))
         (em (%sv-bytes-be m em-len))
         (h-len 48) (salt-len 48))
    (when (or (>= s n) (/= (aref em (- em-len 1)) #xbc)) (return-from %sv-rsa-pss-verify nil))
    (let* ((m-hash (%sv-sha384 msg))
           (db-len (- em-len h-len 1))
           (masked (%sv-slice em 0 db-len))
           (h (%sv-slice em db-len (+ db-len h-len)))
           (db (%sv-xor masked (%sv-mgf1 h db-len))))
      ;; RFC 8017 9.1.2 step 6: the unused top bit is checked on maskedDB (before the XOR),
      ;; and is cleared in DB afterwards.
      (when (/= (logand (aref masked 0) #x80) 0) (return-from %sv-rsa-pss-verify nil))
      (setf (aref db 0) (logand (aref db 0) #x7f))
      (let ((ps-end (- db-len salt-len 1)))
        (dotimes (i ps-end)
          (unless (zerop (aref db i)) (return-from %sv-rsa-pss-verify nil)))
        (unless (= (aref db ps-end) 1) (return-from %sv-rsa-pss-verify nil))
        (let* ((salt (%sv-slice db (+ ps-end 1) db-len))
               (h2 (%sv-sha384 (%sv-cat (make-array 8 :element-type '(unsigned-byte 8) :initial-element 0)
                                        m-hash salt))))
          (%sv-same h h2))))))

;;; ---- ECDSA over secp384r1 (affine; FIPS 186-4 6.4) ----
(defparameter +p384+ (+ (- (expt 2 384) (expt 2 128) (expt 2 96)) (expt 2 32) -1))   ; 2^384 - 2^128 - 2^96 + 2^32 - 1
(defparameter +n384+ #xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC7634D81F4372DDF581A0DB248B0A77AECEC196ACCC52973)
(defparameter +b384+ #xB3312FA7E23EE7E4988E056BE3F82D19181D9C6EFE8141120314088F5013875AC656398D8A2ED19D2A85C8EDD3EC2AEF)
(defparameter +gx384+ #xAA87CA22BE8B05378EB1C71EF320AD746E1D3B628BA79B9859F741E082542A385502F25DBF55296C3A545E3872760AB7)
(defparameter +gy384+ #x3617DE4A96262C6F5D9E98BF9292DC29F8F41DBD289A147CE9DA3113B5F0B8C00A60B1CE1D7E819D7A431D7C90EA0E5F)

(defun %sv-inv (a m)
  (let ((r0 m) (r1 (mod a m)) (t0 0) (t1 1))
    (loop (when (zerop r1) (return (mod t0 m)))
          (let* ((q (floor r0 r1))
                 (nr (- r0 (* q r1)))
                 (nt (- t0 (* q t1))))
            (setq r0 r1) (setq r1 nr)
            (setq t0 t1) (setq t1 nt)))))
(defun %sv-ec-add (p1 p2)
  "Points are (x y) or NIL for infinity."
  (cond ((null p1) p2) ((null p2) p1)
        (t (let ((x1 (first p1)) (y1 (second p1)) (x2 (first p2)) (y2 (second p2)))
             (progn
               (cond ((and (= x1 x2) (/= (mod (+ y1 y2) +p384+) 0))
                      (let* ((l (mod (* (+ (* 3 x1 x1) (- 3)) (%sv-inv (* 2 y1) +p384+)) +p384+))
                             (x3 (mod (- (* l l) x1 x1) +p384+))
                             (y3 (mod (- (* l (- x1 x3)) y1) +p384+)))
                        (list x3 y3)))
                     ((= x1 x2) nil)
                     (t (let* ((l (mod (* (- y2 y1) (%sv-inv (- x2 x1) +p384+)) +p384+))
                               (x3 (mod (- (* l l) x1 x2) +p384+))
                               (y3 (mod (- (* l (- x1 x3)) y1) +p384+)))
                          (list x3 y3)))))))))
(defun %sv-ec-mul (k pt)
  (let ((r nil) (q pt))
    (loop (when (<= k 0) (return r))
          (when (oddp k) (setq r (%sv-ec-add r q)))
          (setq q (%sv-ec-add q q))
          (setq k (floor k 2)))))
(defun %sv-ecdsa-verify (qx qy msg-hash r s)
  "Standard ECDSA verify over P-384 with the SHA-384 digest MSG-HASH (48 bytes)."
  (when (not (and (< 0 r +n384+) (< 0 s +n384+))) (return-from %sv-ecdsa-verify nil))
  (let* ((e (%sv-int-be msg-hash 0 (length msg-hash)))
         (w (%sv-inv s +n384+))
         (u1 (mod (* e w) +n384+))
         (u2 (mod (* r w) +n384+))
         (pt (%sv-ec-add (%sv-ec-mul u1 (list +gx384+ +gy384+)) (%sv-ec-mul u2 (list qx qy)))))
    (and pt (= (mod (first pt) +n384+) r))))

;;; ---- the report's own fields against the certificates and the policy ----
(defparameter +sv-oid-hwid+ (list #x2b #x06 #x01 #x04 #x01 #x9c #x78 #x01 #x04))
(defparameter +sv-oid-tcb+
  (list (cons (list #x2b #x06 #x01 #x04 #x01 #x9c #x78 #x01 #x03 #x01) #x180)      ; bootloader SPL
        (cons (list #x2b #x06 #x01 #x04 #x01 #x9c #x78 #x01 #x03 #x02) #x181)      ; TEE SPL
        (cons (list #x2b #x06 #x01 #x04 #x01 #x9c #x78 #x01 #x03 #x03) #x186)      ; SNP SPL
        (cons (list #x2b #x06 #x01 #x04 #x01 #x9c #x78 #x01 #x03 #x08) #x187)))    ; microcode SPL
(defun %sv-ext-int (value)
  "The INTEGER inside an extension's OCTET STRING content (a DER INTEGER TLV)."
  (let ((x (%sv-tlv value 0))) (%sv-int-be value (second x) (third x))))
(defun %sv-check-binding (rep vcek)
  "T when the report's chip ID (if the report has one), TCB and debug policy agree with VCEK."
  (let* ((exts (nth 7 vcek))
         (chip (%sv-slice rep #x1a0 #x1e0))
         (chip-ok (or (every #'zerop chip)          ; VLEK reports carry no chip ID
                      (let ((h (%sv-ext exts +sv-oid-hwid+))) (and h (%sv-same h chip)))))
         (tcb-ok (every (lambda (pair)
                          (let ((v (%sv-ext exts (car pair))))
                            (and v (= (%sv-ext-int v) (aref rep (cdr pair))))))
                        +sv-oid-tcb+))
         (policy (%sv-int-le rep 8 16))
         (debug-off (not (logbitp 19 policy)))
         (vmpl0 (= (%sv-int-le rep #x30 #x34) 0)))
    (and (%sv-check "chip_id matches the certificate (or report is VLEK-scoped)" chip-ok)
         (%sv-check "reported TCB matches the certificate extensions" tcb-ok)
         (%sv-check "policy: debug disabled" debug-off)
         (%sv-check "report was produced at VMPL0 (the guest's own level)" vmpl0))))
(defun %sv-check-time (cert label)
  (let* ((now (- (get-universal-time) 2208988800))
         (ok (and (<= (nth 5 cert) now) (<= now (nth 6 cert)))))
    (%sv-check (concatenate 'string label " is within its validity period") ok)))

;;; ---- the whole chain ----
(defparameter +sv-rsassa-pss-oid+ (list #x2a #x86 #x48 #x86 #xf7 #x0d #x01 #x01 #x0a))
(defun %sv-is-pss (alg-bytes)
  "T when the AlgorithmIdentifier bytes contain the rsassa-pss OID (1.2.840.113549.1.1.10)."
  (let ((oid +sv-rsassa-pss-oid+) (n (length alg-bytes)))
    (dotimes (i (- n (length oid)) nil)
      (when (loop for k from 0 below (length oid)
                  always (= (aref alg-bytes (+ i k)) (nth k oid)))
        (return t)))))
(defun %sv-check (label ok) (format t "~A: ~A~%" label (if ok "PASS" "FAIL")) ok)

(defun snp-verify-report (rep ark-der ask-der vcek-der)
  "REP: the 1184-byte report.  The three certificates as DER.  T only if every link holds."
  (let* ((ark (%sv-parse-cert ark-der))
         (ask (%sv-parse-cert ask-der))
         (vcek (%sv-parse-cert vcek-der))
         (ok t))
    (flet ((pss-link (label signer-key subject)
             (let ((k (%sv-rsa-key (nth 4 signer-key))))
               (%sv-check label (%sv-rsa-pss-verify (first k) (second k) (nth 0 subject) (nth 2 subject))))))
      (setq ok (and (%sv-check "ARK is RSASSA-PSS (SHA-384 profile)" (%sv-is-pss (nth 1 ark))) ok))
      (setq ok (and (%sv-check "ASK is RSASSA-PSS (SHA-384 profile)" (%sv-is-pss (nth 1 ask))) ok))
      (setq ok (and (%sv-check "VCEK is RSASSA-PSS (SHA-384 profile)" (%sv-is-pss (nth 1 vcek))) ok))
      (setq ok (and (pss-link "ARK self-signed" ark ark) ok))
      (setq ok (and (pss-link "ASK signed by ARK" ark ask) ok))
      (setq ok (and (pss-link "VCEK signed by ASK" ask vcek) ok)))
    (let* ((key (nth 4 vcek))
           (ec-ok (and (= (length key) 97) (= (aref key 0) 4)))
           (qx (%sv-int-be key 1 49)) (qy (%sv-int-be key 49 97))
           (r (%sv-int-le rep #x2a0 (+ #x2a0 72)))
           (s (%sv-int-le rep #x2e8 (+ #x2e8 72)))
           (digest (%sv-sha384 (%sv-slice rep 0 #x2a0)))
           (sig-ok (and ec-ok (%sv-ecdsa-verify-fast qx qy digest r s))))
      (setq ok (and (%sv-check "report signed by the VCEK (ECDSA P-384)" sig-ok) ok)))
    (setq ok (and (%sv-check-time ark "ARK") (%sv-check-time ask "ASK") (%sv-check-time vcek "VCEK/VLEK") ok))
    (setq ok (and (%sv-check-binding rep vcek) ok))
    ok))

;;; ---- ECDSA, fast: Jacobian coordinates (no inversion per step) and Shamir's trick ----
;;; A point is (X Y Z) with affine x = X/Z^2, y = Y/Z^3; NIL is the point at infinity.
;;; Formulas: "dbl-2001-b" (a = -3) and "add-2007-bl".  The affine code above is kept as the
;;; reference: %sv-jac-selftest checks the fast path against it.
(defun %sv-jac-from-affine (p)
  (if (null p) nil (list (first p) (second p) 1)))
(defun %sv-jac-to-affine (j)
  (if (or (null j) (zerop (third j))) nil
      (let* ((zi (%sv-inv (third j) +p384+))
             (zi2 (mod (* zi zi) +p384+))
             (zi3 (mod (* zi2 zi) +p384+)))
        (list (mod (* (first j) zi2) +p384+) (mod (* (second j) zi3) +p384+)))))
(defun %sv-jac-double (j)
  (if (or (null j) (zerop (second j))) nil
      (destructuring-bind (x y z) j
        (let* ((p +p384+)
               (delta (mod (* z z) p))
               (gamma (mod (* y y) p))
               (beta (mod (* x gamma) p))
               (alpha (mod (* 3 (* (- x delta) (+ x delta))) p))
               (x3 (mod (- (* alpha alpha) (* 8 beta)) p))
               (z3 (mod (- (* (+ y z) (+ y z)) gamma delta) p))
               (y3 (mod (- (* alpha (- (* 4 beta) x3)) (* 8 (* gamma gamma))) p)))
          (list x3 y3 z3)))))
(defun %sv-jac-add (j1 j2)
  (cond ((null j1) j2)
        ((null j2) j1)
        (t (destructuring-bind (x1 y1 z1) j1
             (destructuring-bind (x2 y2 z2) j2
               (let* ((p +p384+)
                      (z1z1 (mod (* z1 z1) p))
                      (z2z2 (mod (* z2 z2) p))
                      (u1 (mod (* x1 z2z2) p))
                      (u2 (mod (* x2 z1z1) p))
                      (s1 (mod (* y1 (mod (* z2 z2z2) p)) p))
                      (s2 (mod (* y2 (mod (* z1 z1z1) p)) p))
                      (h (mod (- u2 u1) p))
                      (r (mod (* 2 (- s2 s1)) p)))
                 (cond ((zerop h)
                        (if (zerop r) (%sv-jac-double j1) nil))
                       (t
                        (let* ((i4 (mod (* (* 2 h) (* 2 h)) p))
                               (j (mod (* h i4) p))
                               (v (mod (* u1 i4) p))
                               (x3 (mod (- (* r r) j (* 2 v)) p))
                               (y3 (mod (- (* r (- v x3)) (* 2 (mod (* s1 j) p))) p))
                               (z3 (mod (* (- (* (+ z1 z2) (+ z1 z2)) z1z1 z2z2) h) p)))
                          (list x3 y3 z3))))))))))
(defun %sv-jac-mul (k pt)
  "k * PT (PT affine) by left-to-right double-and-add in Jacobian coordinates."
  (let ((acc nil) (base (%sv-jac-from-affine pt)))
    (dotimes (i (integer-length k) (%sv-jac-to-affine acc))
      (setq acc (%sv-jac-double acc))
      (when (logbitp (- (integer-length k) 1 i) k)
        (setq acc (%sv-jac-add acc base))))))
(defun %sv-shamir (u1 g u2 q)
  "u1*G + u2*Q (affine in, affine out) with one shared doubling chain."
  (let* ((jg (%sv-jac-from-affine g)) (jq (%sv-jac-from-affine q))
         (jgq (%sv-jac-add jg jq))
         (acc nil)
         (bits (max (integer-length u1) (integer-length u2))))
    (dotimes (i bits)
      (let ((b (- bits 1 i)))
        (setq acc (%sv-jac-double acc))
        (let ((x1 (logbitp b u1)) (x2 (logbitp b u2)))
          (cond ((and x1 x2) (setq acc (%sv-jac-add acc jgq)))
                (x1 (setq acc (%sv-jac-add acc jg)))
                (x2 (setq acc (%sv-jac-add acc jq)))))))
    (%sv-jac-to-affine acc)))
(defun %sv-ecdsa-verify-fast (qx qy msg-hash r s)
  (when (not (and (< 0 r +n384+) (< 0 s +n384+))) (return-from %sv-ecdsa-verify-fast nil))
  (let* ((e (%sv-int-be msg-hash 0 (length msg-hash)))
         (w (%sv-inv s +n384+))
         (u1 (mod (* e w) +n384+))
         (u2 (mod (* r w) +n384+))
         (pt (%sv-shamir u1 (list +gx384+ +gy384+) u2 (list qx qy))))
    (and pt (= (mod (first pt) +n384+) r))))
(defun %sv-jac-selftest ()
  "The fast path must agree with the affine reference on several scalars."
  (let ((g (list +gx384+ +gy384+)) (ok t))
    (dolist (k (list 1 2 3 1000003 (- +n384+ 5) #x1234567890abcdef1234567890abcdef))
      (unless (equal (%sv-jac-mul k g) (%sv-ec-mul k g)) (setq ok nil)))
    (let ((q (%sv-ec-mul 987654321 g)))
      (unless (equal (%sv-shamir 555 g 777 q) (%sv-ec-add (%sv-ec-mul 555 g) (%sv-ec-mul 777 q)))
        (setq ok nil)))
    ok))
