;;;; test/snp/snp-verify.lisp -- SEV-SNP report verification in Lisp, end to end:
;;;;   ARK --RSA-PSS--> ASK --RSA-PSS--> VCEK (or VLEK)  --ECDSA P-384--> REPORT
;;;; Hosted CLI.  Usage (see test/snp/verify-chain-test.lisp for a driver):
;;;;   (snp-verify-report REPORT-BYTES ARK-DER ASK-DER VCEK-DER)  => T / NIL, printing each step.
;;;; Profile (checked, anything else is refused): RSA-PSS with SHA-384, MGF1-SHA-384,
;;;; salt 48, public exponent 65537 for ARK/ASK; ECDSA on secp384r1 with SHA-384 for the report.
;;;; Depends on: sha512 family in net/crypto.lisp (sha512-init, sha512-block), bignum integers.

;;; ---- bytes and integers ----
(defun %sv-int-be (v s e)
  (let ((n 0)) (do ((i s (+ i 1))) ((>= i e) n) (setq n (+ (* n 256) (aref v i))))))
(defun %sv-int-le (v s e)
  (let ((n 0)) (do ((i (- e 1) (- i 1))) ((< i s) n) (setq n (+ (* n 256) (aref v i))))))
(defun %sv-bytes-be (n len)
  (let ((v (make-array len :element-type '(unsigned-byte 8))) (x n))
    (do ((i (- len 1) (- i 1))) ((< i 0) v)
      (setf (aref v i) (mod x 256)) (setq x (floor x 256)))))
(defun %sv-cat (&rest vs)
  (let* ((n (reduce #'+ vs :key #'length))
         (out (make-array n :element-type '(unsigned-byte 8))) (k 0))
    (dolist (v vs out)
      (dotimes (i (length v)) (setf (aref out k) (aref v i)) (setq k (+ k 1))))))
(defun %sv-slice (v s e)
  (let ((out (make-array (- e s) :element-type '(unsigned-byte 8))))
    (dotimes (i (- e s) out) (setf (aref out i) (aref v (+ s i))))))
(defun %sv-same (a b)
  (and (= (length a) (length b))
       (let ((ok t)) (dotimes (i (length a) ok) (unless (= (aref a i) (aref b i)) (setq ok nil))))))
(defun %sv-xor (a b)
  (let ((out (make-array (length a) :element-type '(unsigned-byte 8))))
    (dotimes (i (length a) out) (setf (aref out i) (logxor (aref a i) (aref b i))))))

;;; ---- SHA-384 (SHA-512 with its own IV, truncated) ----
(defun %sv-sha384 (msg)
  (sha512-init)
  (let* ((msg-len (length msg))
         (full (* 128 (floor msg-len 128)))
         (rem (- msg-len full))
         (tlen (if (< rem 112) 128 256))
         (tail (make-array tlen :element-type '(unsigned-byte 8) :initial-element 0))
         (h (make-array 64 :element-type '(unsigned-byte 8)))
         (w (make-array 640)))
    (let ((iv (list #xcbbb9d5dc1059ed8 #x629a292a367cd507 #x9159015a3070dd17 #x152fecd8f70e5939
                    #x67332667ffc00b31 #x8eb44a8768581511 #xdb0c2e0d64f98fa7 #x47b5481dbefa4fa4)))
      (let ((i 0))
        (dolist (x iv)
          (dotimes (b 8) (setf (aref h (+ (* i 8) b)) (ldb (byte 8 (* 8 (- 7 b))) x)))
          (setq i (+ i 1)))))
    (let ((offset 0))
      (loop (when (not (< offset full)) (return ()))
            (sha512-block msg offset h w)
            (setq offset (+ offset 128))))
    (dotimes (i rem) (setf (aref tail i) (aref msg (+ full i))))
    (setf (aref tail rem) #x80)
    (let ((bits (* msg-len 8)) (hi (ash msg-len -29)))
      (dotimes (k 8)
        (setf (aref tail (- tlen 1 k)) (ldb (byte 8 (* 8 k)) bits))
        (setf (aref tail (- tlen 9 k)) (ldb (byte 8 (* 8 k)) hi))))
    (sha512-block tail 0 h w)
    (when (= tlen 256) (sha512-block tail 128 h w))
    (%sv-slice h 0 48)))

;;; ---- DER ----
(defun %sv-tlv (v pos)
  "(tag content-start content-end) for the element at POS."
  (let* ((tag (aref v pos)) (b (aref v (+ pos 1))) (cs 0) (len 0))
    (if (< b 128)
        (setq cs (+ pos 2) len b)
        (let ((nb (- b 128)))
          (setq len (%sv-int-be v (+ pos 2) (+ pos 2 nb)))
          (setq cs (+ pos 2 nb))))
    (list tag cs (+ cs len))))
(defun %sv-children (v s e)
  "List of (tag cs ce start) for the TLVs fully inside [s, e)."
  (let ((out nil) (pos s))
    (loop (when (>= pos e) (return (nreverse out)))
          (let ((x (%sv-tlv v pos)))
            (push (list (first x) (second x) (third x) pos) out)
            (setq pos (third x))))))
(defun %sv-oid-bytes (v tlv) (%sv-slice v (second tlv) (third tlv)))

;;; ---- certificates: (values tbs-bytes sig-alg-bytes sig-bytes spki-alg spki-key) ----
(defun %sv-parse-cert (der)
  (let* ((cert (%sv-tlv der 0))
         (kids (%sv-children der (second cert) (third cert)))
         (tbs-k (first kids)) (alg-k (second kids)) (sig-k (third kids))
         (tbs-bytes (%sv-slice der (fourth tbs-k) (third tbs-k)))
         (tbs-inner (%sv-children der (second tbs-k) (third tbs-k)))
         (has-version (= (first (first tbs-inner)) #xa0))
         (spki (nth (if has-version 6 5) tbs-inner))
         (spki-kids (%sv-children der (second spki) (third spki)))
         (spki-alg (first spki-kids))
         (spki-key-bits (second spki-kids))
         (sig-alg-bytes (%sv-slice der (fourth alg-k) (third alg-k)))
         (sig-bytes (%sv-slice der (+ (second sig-k) 1) (third sig-k)))
         (key-bytes (%sv-slice der (+ (second spki-key-bits) 1) (third spki-key-bits)))
         (alg-oid (%sv-oid-bytes der (first (%sv-children der (second spki-alg) (third spki-alg))))))
    (list tbs-bytes sig-alg-bytes sig-bytes alg-oid key-bytes)))

(defun %sv-rsa-key (key-bytes)
  "The RSAPublicKey inside a BIT STRING payload: (n e)."
  (let* ((seq (%sv-tlv key-bytes 0))
         (ints (%sv-children key-bytes (second seq) (third seq)))
         (n (%sv-int-be key-bytes (second (first ints)) (third (first ints))))
         (e (%sv-int-be key-bytes (second (second ints)) (third (second ints)))))
    (list n e)))

;;; ---- RSA-PSS (RFC 8017 8.1.2), SHA-384 / MGF1-SHA-384 / salt 48 / e = 65537 ----
(defun %sv-modexp (base e n)
  (let ((r 1) (b (mod base n)) (x e))
    (loop (when (<= x 0) (return r))
          (when (oddp x) (setq r (mod (* r b) n)))
          (setq b (mod (* b b) n))
          (setq x (floor x 2)))))
(defun %sv-mgf1 (seed len)
  (let ((out nil) (count 0) (got 0))
    (loop (when (>= got len) (return))
          (let ((h (%sv-sha384 (%sv-cat seed (%sv-bytes-be count 4)))))
            (push h out) (setq got (+ got 48)) (setq count (+ count 1))))
    (%sv-slice (apply #'%sv-cat (nreverse out)) 0 len)))
(defun %sv-rsa-pss-verify (n e msg sig)
  "T when SIG is a valid RSASSA-PSS (SHA-384, MGF1-SHA-384, salt 48) signature of MSG under (n, e)."
  (let* ((s (%sv-int-be sig 0 (length sig)))
         (m (%sv-modexp s e n))
         (em-bits (- (integer-length n) 1))
         (em-len (ceiling em-bits 8))
         (em (%sv-bytes-be m em-len))
         (h-len 48) (salt-len 48))
    (when (or (>= s n) (/= (aref em (- em-len 1)) #xbc)) (return-from %sv-rsa-pss-verify nil))
    (let* ((m-hash (%sv-sha384 msg))
           (db-len (- em-len h-len 1))
           (masked (%sv-slice em 0 db-len))
           (h (%sv-slice em db-len (+ db-len h-len)))
           (db (%sv-xor masked (%sv-mgf1 h db-len))))
      ;; RFC 8017 9.1.2 step 6: the unused top bit is checked on maskedDB (before the XOR),
      ;; and is cleared in DB afterwards.
      (when (/= (logand (aref masked 0) #x80) 0) (return-from %sv-rsa-pss-verify nil))
      (setf (aref db 0) (logand (aref db 0) #x7f))
      (let ((ps-end (- db-len salt-len 1)))
        (dotimes (i ps-end)
          (unless (zerop (aref db i)) (return-from %sv-rsa-pss-verify nil)))
        (unless (= (aref db ps-end) 1) (return-from %sv-rsa-pss-verify nil))
        (let* ((salt (%sv-slice db (+ ps-end 1) db-len))
               (h2 (%sv-sha384 (%sv-cat (make-array 8 :element-type '(unsigned-byte 8) :initial-element 0)
                                        m-hash salt))))
          (%sv-same h h2))))))

;;; ---- ECDSA over secp384r1 (affine; FIPS 186-4 6.4) ----
(defparameter +p384+ (+ (- (expt 2 384) (expt 2 128) (expt 2 96)) (expt 2 32) -1))   ; 2^384 - 2^128 - 2^96 + 2^32 - 1
(defparameter +n384+ #xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFC7634D81F4372DDF581A0DB248B0A77AECEC196ACCC52973)
(defparameter +b384+ #xB3312FA7E23EE7E4988E056BE3F82D19181D9C6EFE8141120314088F5013875AC656398D8A2ED19D2A85C8EDD3EC2AEF)
(defparameter +gx384+ #xAA87CA22BE8B05378EB1C71EF320AD746E1D3B628BA79B9859F741E082542A385502F25DBF55296C3A545E3872760AB7)
(defparameter +gy384+ #x3617DE4A96262C6F5D9E98BF9292DC29F8F41DBD289A147CE9DA3113B5F0B8C00A60B1CE1D7E819D7A431D7C90EA0E5F)

(defun %sv-inv (a m)
  (let ((r0 m) (r1 (mod a m)) (t0 0) (t1 1))
    (loop (when (zerop r1) (return (mod t0 m)))
          (let* ((q (floor r0 r1))
                 (nr (- r0 (* q r1)))
                 (nt (- t0 (* q t1))))
            (setq r0 r1) (setq r1 nr)
            (setq t0 t1) (setq t1 nt)))))
(defun %sv-ec-add (p1 p2)
  "Points are (x y) or NIL for infinity."
  (cond ((null p1) p2) ((null p2) p1)
        (t (let ((x1 (first p1)) (y1 (second p1)) (x2 (first p2)) (y2 (second p2)))
             (progn
               (cond ((and (= x1 x2) (/= (mod (+ y1 y2) +p384+) 0))
                      (let* ((l (mod (* (+ (* 3 x1 x1) (- 3)) (%sv-inv (* 2 y1) +p384+)) +p384+))
                             (x3 (mod (- (* l l) x1 x1) +p384+))
                             (y3 (mod (- (* l (- x1 x3)) y1) +p384+)))
                        (list x3 y3)))
                     ((= x1 x2) nil)
                     (t (let* ((l (mod (* (- y2 y1) (%sv-inv (- x2 x1) +p384+)) +p384+))
                               (x3 (mod (- (* l l) x1 x2) +p384+))
                               (y3 (mod (- (* l (- x1 x3)) y1) +p384+)))
                          (list x3 y3)))))))))
(defun %sv-ec-mul (k pt)
  (let ((r nil) (q pt))
    (loop (when (<= k 0) (return r))
          (when (oddp k) (setq r (%sv-ec-add r q)))
          (setq q (%sv-ec-add q q))
          (setq k (floor k 2)))))
(defun %sv-ecdsa-verify (qx qy msg-hash r s)
  "Standard ECDSA verify over P-384 with the SHA-384 digest MSG-HASH (48 bytes)."
  (when (not (and (< 0 r +n384+) (< 0 s +n384+))) (return-from %sv-ecdsa-verify nil))
  (let* ((e (%sv-int-be msg-hash 0 (length msg-hash)))
         (w (%sv-inv s +n384+))
         (u1 (mod (* e w) +n384+))
         (u2 (mod (* r w) +n384+))
         (pt (%sv-ec-add (%sv-ec-mul u1 (list +gx384+ +gy384+)) (%sv-ec-mul u2 (list qx qy)))))
    (and pt (= (mod (first pt) +n384+) r))))

;;; ---- the whole chain ----
(defparameter +sv-rsassa-pss-oid+ (list #x2a #x86 #x48 #x86 #xf7 #x0d #x01 #x01 #x0a))
(defun %sv-is-pss (alg-bytes)
  "T when the AlgorithmIdentifier bytes contain the rsassa-pss OID (1.2.840.113549.1.1.10)."
  (let ((oid +sv-rsassa-pss-oid+) (n (length alg-bytes)))
    (dotimes (i (- n (length oid)) nil)
      (when (loop for k from 0 below (length oid)
                  always (= (aref alg-bytes (+ i k)) (nth k oid)))
        (return t)))))
(defun %sv-check (label ok) (format t "~A: ~A~%" label (if ok "PASS" "FAIL")) ok)

(defun snp-verify-report (rep ark-der ask-der vcek-der)
  "REP: the 1184-byte report.  The three certificates as DER.  T only if every link holds."
  (let* ((ark (%sv-parse-cert ark-der))
         (ask (%sv-parse-cert ask-der))
         (vcek (%sv-parse-cert vcek-der))
         (ok t))
    (flet ((pss-link (label signer-key subject)
             (let ((k (%sv-rsa-key (nth 4 signer-key))))
               (%sv-check label (%sv-rsa-pss-verify (first k) (second k) (nth 0 subject) (nth 2 subject))))))
      (setq ok (and (%sv-check "ARK is RSASSA-PSS (SHA-384 profile)" (%sv-is-pss (nth 1 ark))) ok))
      (setq ok (and (%sv-check "ASK is RSASSA-PSS (SHA-384 profile)" (%sv-is-pss (nth 1 ask))) ok))
      (setq ok (and (%sv-check "VCEK is RSASSA-PSS (SHA-384 profile)" (%sv-is-pss (nth 1 vcek))) ok))
      (setq ok (and (pss-link "ARK self-signed" ark ark) ok))
      (setq ok (and (pss-link "ASK signed by ARK" ark ask) ok))
      (setq ok (and (pss-link "VCEK signed by ASK" ask vcek) ok)))
    (let* ((key (nth 4 vcek))
           (ec-ok (and (= (length key) 97) (= (aref key 0) 4)))
           (qx (%sv-int-be key 1 49)) (qy (%sv-int-be key 49 97))
           (r (%sv-int-le rep #x2a0 (+ #x2a0 72)))
           (s (%sv-int-le rep #x2e8 (+ #x2e8 72)))
           (digest (%sv-sha384 (%sv-slice rep 0 #x2a0)))
           (sig-ok (and ec-ok (%sv-ecdsa-verify qx qy digest r s))))
      (setq ok (and (%sv-check "report signed by the VCEK (ECDSA P-384)" sig-ok) ok)))
    ok))
