;;; bind-probe.lisp -- what a dynamic binding of a special must do.
(defun p (l v) (format t "~a ~s~%" l v))
(defvar *a* :outer)
(defvar *b* 0)
(defun peek () *a*)
(defun poke (v) (setq *a* v))

(p "base"        *a*)
(p "sees"        (let ((*a* :inner)) (peek)))
(p "restored"    (progn (let ((*a* :inner)) (peek)) *a*))
(p "setq-inside" (let ((*a* :inner)) (poke :poked) (peek)))
(p "no-leak"     (progn (let ((*a* :inner)) (poke :poked)) *a*))
(p "nested"      (let ((*a* 1)) (list *a* (let ((*a* 2)) (list *a* (let ((*a* 3)) *a*) *a*)) *a*)))
(p "after-nest"  *a*)
(p "throw-out"   (list (catch 'x (let ((*a* :inner)) (throw 'x (peek)))) *a*))
(p "error-out"   (list (handler-case (let ((*a* :inner)) (error "e")) (error (c) (declare (ignore c)) :caught)) *a*))
(p "block-out"   (list (block bk (let ((*a* :inner)) (return-from bk (peek)))) *a*))
(p "uw-protect"  (let ((seen nil))
                   (list (catch 'y (unwind-protect (let ((*a* :inner)) (throw 'y (peek)))
                                     (setq seen *a*)))
                         seen *a*)))
(p "let*-inits"  (let* ((*b* 5) (*a* (+ *b* 1))) (list *a* *b*)))
(p "after-let*"  (list *a* *b*))
(p "progv"       (list (progv (list '*a*) (list :pv) (peek)) *a*))
(p "fresh"       (let ((*never-before-bound-qq* 7))
                   (declare (special *never-before-bound-qq*))
                   (symbol-value '*never-before-bound-qq*)))
(p "fresh-after" (boundp '*never-before-bound-qq*))
(p "closure"     (let ((f (let ((*a* :inner)) (lambda () *a*)))) (list (funcall f) *a*)))
(p "loop-bind"   (let ((acc nil)) (dotimes (i 3) (let ((*a* i)) (push (peek) acc))) (list (reverse acc) *a*)))
(p "done" t)
