(defvar *da* :global-a)
(defun p (l v) (format t "  ~a ~s~%" l v))
(defun probe (tag)
  (format t "-- ~a~%" tag)
  (p "armed-word" (mem-ref #x10000DB8 :u32))
  (let ((blk (%dynb-block)))
    (p "dynb-block" blk)
    (unless (eql blk 0)
      (p "depth-outside" (%dynb-depth blk))))
  (let ((obj (list 7)))
    (let ((*da* obj))
      (let ((blk (%dynb-block)))
        (unless (eql blk 0)
          (p "depth-inside" (%dynb-depth blk))
          (p "find-hit" (%dynb-find (%global-name-key '*da*)
                                    (- (%dynb-next blk) 16)
                                    (- (%dynb-depth blk) 1)))))
      (p "read-inside" *da*)
      (p "eq-inside" (eq *da* obj))
      (p "symval-inside" (symbol-value '*da*))))
  (p "read-after" *da*))
(probe "MAIN")
(let ((th (sb-thread:make-thread (lambda () (probe "WORKER") 0))))
  (sb-thread:join-thread th))
(probe "MAIN-AFTER")
