;;;; gen-word-boundary.lisp -- regenerates test/word-boundary.lisp from SBCL.
;;;; Run from the repo root:  sbcl --script test/gen-word-boundary.lisp

(defvar *xs* (list 0 1 -1 7 -7 16388 536870911 536870912 -536870912 -536870913 1073741823 -1073741823 1073741824 2147483647 -2147483648 4294967295))
(defvar *forms*
  '((ash x 1) (ash x 16) (ash x 30) (ash x 31) (ash x -1) (ash x -16) (ash x -29) (ash x -40)
    (logand x 255) (logand x -2) (logand x 1073741823) (logand x (- x))
    (logior x 1) (logior x 1073741824) (logxor x -1) (lognot x)
    (1+ x) (1- x) (* x 3) (* x x) (- x) (+ x x)
    (evenp x) (oddp x) (plusp x) (minusp x) (zerop x)
    (ldb (byte 8 0) x) (ldb (byte 8 24) x) (logbitp 29 x) (logcount x)
    (floor x 7) (mod x 1000) (truncate x -3) (rem x 10)
    (< x 536870912) (> x -536870912) (= x 1073741823) (max x 0)))
(with-open-file (o "test/word-boundary.lisp" :direction :output :if-exists :supersede)
  (format o ";;;; word-boundary.lisp -- integer ops at the machine-word boundaries.
;;;;
;;;; Run: ./modus --script test/word-boundary.lisp   (any CLI: x64, i386, RV32)
;;;;
;;;; Each op is evaluated through mvm-eval on operands around 2^29, 2^30 and
;;;; 2^31: fixnum-sized on the 62-bit tower, the WORD EDGE on the 30-bit one,
;;;; where a fixnum's machine word no longer fits a Lisp fixnum.  EXPECTED
;;;; values were generated by SBCL.  Every case binds x to a LITERAL so the
;;;; compiler knows its width and takes the typed fast paths -- through a
;;;; lambda parameter the width is unknown and the guarded path hid the bug.  Before the
;;;; interpreter's word ops became exact (interp.lisp, %%MVM-WORD), a 30-bit
;;;; port got (ash 16388 16), (ash x 30) and every tag test on a fixnum >= 2^29
;;;; wrong.
;;;;
;;;; ONE TOP-LEVEL FORM PER OP, not per case: i386 --script dies at its first
;;;; collection during a long script (pre-existing, open), and 624 top-level
;;;; forms allocate enough to reach it.

(defvar *wb-fail* 0)
(defvar *wb-n* 0)
(defun wb-same (got want)
  ;; = for numbers: -2^fixnum-bits is a machine word but the runtime keeps it a
  ;; BIGNUM (most-negative-fixnum is never a fixnum), while raw ops such as
  ;; (logand x -2) produce it as a raw word, natively as well as interpreted.
  (if (and (numberp got) (numberp want)) (= got want) (equal got want)))
(defun wb (name gots xs wants)
  (loop for x in xs for want in wants for got in gots
        do (progn
             (setq *wb-n* (+ *wb-n* 1))
             (unless (wb-same got want)
               (setq *wb-fail* (+ *wb-fail* 1))
               (format t \"~~&FAIL ~~S x=~~S got ~~S want ~~S~~%%\" name x got want)))))
(defvar *xs* '~S)

" *xs*)
  (dolist (f *forms*)
    ;; Each case binds x to a LITERAL, so the compiler knows its width and
    ;; takes its typed fast paths -- the ones that went wrong.  (Through a
    ;; lambda parameter the width is unknown and the guarded path hides it.)
    (format o "(wb '~S~%    (list~{ ~S~})~%    *xs* '~S)~%"
            f (mapcar (lambda (x) `(let ((x ,x)) ,f)) *xs*)
            (mapcar (lambda (x) (eval `(let ((x ,x)) ,f))) *xs*)))
  (format o "~%(format t \"~~&word-boundary: ~~D of ~~D passed~~%\" (- *wb-n* *wb-fail*) *wb-n*)~%")
  ;; An uncaught ERROR is what makes --script exit 1; SYS-EXIT called from a
  ;; script does not take effect (measured on x64 and i386: it returns).
  (format o "(when (> *wb-fail* 0) (error \"word-boundary: ~~D failure(s)\" *wb-fail*))~%"))
