;;; LOOP: bare/OF-TYPE type specs after MAXIMIZE/MINIMIZE, NAMED loops that
;;; have no BLOCK NIL of their own, and IN/ON ... BY evaluation order.
(defparameter *checks*
  (list
   (list :max-fixnum (loop for x in '(8 20 5 24 1) maximize x fixnum) 24)
   (list :min-of-type (loop for x in '(8 20 5 24 1) minimize x of-type integer) 1)
   (list :max-into (loop for x in '(1 2 3) maximize x into m fixnum finally (return m)) 3)
   (list :sum-fixnum-end (loop for x in '(1 2 3) sum x fixnum) 6)
   (list :named-return (block nil (loop named foo for i = 1 then (return :good)) :bad) :good)
   (list :named-collect (block nil (loop named foo for x in '(a b c) collect (return :good)) :bad) :good)
   (list :named-finally (block nil (loop named foo for x in '(1 2)
                                          do (loop for y in '(3) do (return :inner))
                                          finally (return-from foo :named))) :named)
   (list :named-natural (loop named foo for x in '(1 2 3) collect x) '(1 2 3))
   (list :named-always (loop named foo for x in '(1 2 3) always (plusp x)) t)
   (list :named-finish (loop named foo for x in '(1 2 3) collect x when (= x 2) do (loop-finish)) '(1 2))
   (list :unnamed-return (loop for x in '(1 2 3) when (= x 2) return :two) :two)
   (list :in-by-order (let ((i 0) a b)
                        (loop for e in (progn (setf a (incf i)) '(a b c d))
                              by (progn (setf b (incf i)) #'cddr) collect e)
                        (list a b)) '(1 2))
   (list :on-by-order (let ((i 0) a b)
                        (loop for e on (progn (setf a (incf i)) '(a b c d))
                              by (progn (setf b (incf i)) #'cddr) collect (car e))
                        (list a b)) '(1 2))
   (list :on-dotted (loop for x on '(a b c . d) collect (car x)) '(a b c))
   (list :destr-then (loop for (x . y) = '(a b c d e) then y while x collect x) '(a b c d e))
   (list :with-typed-destr (loop with (a b c) of-type (fixnum float t) return (list a b c)) '(0 0.0 nil))
   (list :with-and-destr (loop with b = 3 and (nil a) = '(1 2) return (list a b)) '(2 3))
   (list :it-first-only (let ((it 'z)) (loop for x in '(a b) when x collect it and collect it)) '(a z b z))
   (list :and-parallel (loop for i from 1 to 5 and j = 0 then (+ j i) collect j) '(0 1 3 6 10))))
(defparameter *bad* (remove-if (lambda (c) (equal (second c) (third c))) *checks*))
(dolist (c *bad*) (format t "~&BAD ~s got ~s want ~s~%" (first c) (second c) (third c)))
(format t "~&loop-named-and-types: ~a~%" (if *bad* "FAIL" "PASS"))
(sys-exit (if *bad* 1 0))
