(load "lib/load-mvm.lisp")
(in-package :modus.mvm)
(with-open-file (s "net/hdmi-hvs.lisp")
  (with-open-file (o "/tmp/claude-1002/hvs-all-forms.txt" :direction :output :if-exists :supersede)
    (let ((*package* (find-package :modus.mvm)) (*print-base* 10) (*print-case* :downcase)
          (*print-pretty* nil) (*print-right-margin* 1000000) (n 0))
      (loop for form = (read s nil :eof) until (eq form :eof)
            when (and (consp form) (member (car form) '(defun defvar defparameter)))
            do (let ((body (cdddr form)))
                 (when (and (eq (car form) 'defun) (stringp (car body)) (cdr body)) (setf body (cdr body)))
                 (format o "~A~%" (prin1-to-string (if (eq (car form) 'defun) (list* 'defun (cadr form) (caddr form) body) form)))
                 (incf n)))
      (format t "WROTE ~D forms~%" n))))
