;;; Enumerate every test the ANSI corpus registers when loaded into SBCL.
;;; Output: one line per test, "FILE NAME".
(defpackage "CL-TEST" (:use "CL"))
(in-package "CL-TEST")
(defvar *cur-file* "?")
(defvar *seen* (make-hash-table :test 'equal))
(defvar *out* nil)
(defun %rec (name)
  (let ((k (format nil "~A" name)))
    (unless (gethash k *seen*)
      (setf (gethash k *seen*) t)
      (push (cons *cur-file* k) *out*))))
(defmacro deftest (name &rest body) (declare (ignore body)) `(%rec ',name))
(defvar *root* "/home/claude/modus/tmp/ansi-test/")
(defun load-forms (path)
  (with-open-file (s path)
    (let ((*package* (find-package "CL-TEST")) (*read-eval* t))
      (loop
        (let ((f (handler-case (read s nil :eof) (error () :bad))))
          (cond ((eq f :eof) (return))
                ((eq f :bad) (handler-case (progn (read-line s nil) nil) (error () (return))))
                (t (handler-case
                       (let ((*error-output* (make-broadcast-stream))
                             (*standard-output* (make-broadcast-stream)))
                         (eval f))
                     (error () nil)))))))))
(setf *cur-file* "AUX")
(dolist (a '("ansi-aux-macros.lsp" "ansi-aux.lsp" "cons-aux.lsp" "types-aux.lsp" "array-aux.lsp" "bit-aux.lsp" "char-aux.lsp" "hash-table-aux.lsp" "numbers-aux.lsp" "random-aux.lsp" "floor-aux.lsp" "ffloor-aux.lsp" "ceiling-aux.lsp" "fceiling-aux.lsp" "truncate-aux.lsp" "ftruncate-aux.lsp" "round-aux.lsp" "fround-aux.lsp" "times-aux.lsp" "division-aux.lsp" "exp-aux.lsp" "gcd-aux.lsp" "string-aux.lsp" "subseq-aux.lsp" "search-aux.lsp" "remove-aux.lsp" "remove-duplicates-aux.lsp" "printer-aux.lsp" "backquote-aux.lsp" "reader-aux.lsp" "package-aux.lsp" "packages00-aux.lsp" "pathnames-aux.lsp" "cl-symbols-aux.lsp" "define-condition-aux.lsp" "defclass-aux.lsp" "sort-aux.lsp" "random-class-aux.lsp"))
  (load-forms (concatenate 'string *root* "auxiliary/" a)))
;; our deftest again, in case aux redefined it
(defmacro deftest (name &rest body) (declare (ignore body)) `(%rec ',name))
(dolist (p (directory (concatenate 'string *root* "**/*.lsp")))
  (let ((dir (car (last (pathname-directory p)))) (nm (pathname-name p)))
    (unless (or (member dir '("auxiliary" "sandbox" "beyond-ansi" "rctest") :test #'string=)
                (string= nm "load"))
      (setf *cur-file* nm)
      (let ((*default-pathname-defaults* (make-pathname :directory (pathname-directory p))))
        (handler-case (load-forms p) (error () nil))))))
(with-open-file (o "/home/claude/modus/tmp/ansi-census/sbcl-tests.txt" :direction :output :if-exists :supersede)
  (dolist (e (reverse *out*)) (format o "~A ~A~%" (car e) (cdr e))))
(format t "~D tests~%" (length *out*))
