;; auto-generated flet/labels battery
(defvar *fb0* 0)
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (flet ((%f () 1))     (%f)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.1" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.1" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (flet ((%f (x) x))     (%f 2)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.2" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.2" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (flet ((%f (&rest args) args))     (%f 'a 'b 'c)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.3" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.3" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (block %f     (flet ((%f (&optional (x (return-from %f :good)))                nil))       (%f)       :bad)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.4" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.4" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (block %f     (flet ((%f (&key (x (return-from %f :good)))                nil))       (%f)       :bad)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.4a" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.4a" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (flet ((%f () (return-from %f 15) 35))     (%f)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.5" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.5" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (block %f     (flet ((%f (&aux (x (return-from %f 10)))                20))       (%f))))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.6" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.6" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (flet ((%f (x) (+ x 5)))     (flet ((%f (y) (cond ((eql y 20) 30)                          (t (%f 20)))))       (%f 15))))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.7" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.7" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (flet ((%f (&key a (b 0 b-p)) (values a b (not (not b-p)))))     (%f)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.8" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.8" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (flet ((%f (&key a (b 0 b-p)) (values a b (not (not b-p)))))     (%f :a 1)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.9" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.9" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (flet ((%f (&key a (b 0 b-p)) (values a b (not (not b-p)))))     (%f :b 2)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.10" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.10" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (flet ((%f (&key a (b 0 b-p)) (values a b (not (not b-p)))))     (%f :b 2 :a 3)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.11" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.11" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (signals-error    (flet ((%f (&key a (b 0 b-p)) (values a b (not (not b-p))))) (%f :c 4))    program-error))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.12" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.12" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (signals-error    (flet ((%f (&key a (b 0 b-p)) (values a b (not (not b-p))))) (%f :a))    program-error))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.13" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.13" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (signals-error (flet ((%f (a) a)) (%f)) program-error))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.14" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.14" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (signals-error (flet ((%f (a) a)) (%f 1 2)) program-error))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.15" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.15" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (signals-error (flet ((%f (&key a) a)) (%f '(foo))) program-error))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.16" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.16" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (flet (((setf %f) (x y) (setf (car y) x)))     (let ((z (list 1 2)))       (setf (%f z) 'a)       z)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.17" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.17" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (flet ((%f (x) (incf x) (+ x x)))     (%f 10)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.18" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.18" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (flet ((%f (a1 a2 a3 a4 a5 a6 a7 a8 a9 a10               b1 b2 b3 b4 b5 b6 b7 b8 b9 b10               c1 c2 c3 c4 c5 c6 c7 c8 c9 c10               d1 d2 d3 d4 d5 d6 d7 d8 d9 d10               e1 e2 e3 e4 e5 e6 e7 e8 e9 e10)              (+ a1 a2 a3 a4 a5 a6 a7 a8 a9 a10                 b1 b2 b3 b4 b5 b6 b7 b8 b9 b10                 c1 c2 c3 c4 c5 c6 c7 c8 c9 c10                 d1 d2 d3 d4 d5 d6 d7 d8 d9 d10                 e1 e2 e3 e4 e5 e6 e7 e8 e9 e10)))     (%f 1 2 3 4 5 6 7 8 9 10         11 12 13 14 15 16 17 18 19 20         21 22 23 24 25 26 27 28 29 30         31 32 33 34 35 36 37 38 39 40         41 42 43 44 45 46 47 48 49 50)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.19" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.19" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (let* ((n (min (1- lambda-parameters-limit) 1024))          (vars (loop repeat n collect (gensym))))     (eval      `(eqlt ,n             (flet ((%f ,vars (+ ,@ vars)))               (%f ,@(loop for e in vars collect 1)))))))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.20" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.20" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (flet ((%f (x)              (declare (type fixnum x))              "Add one to the fixnum x."              (1+ x)))     (declare (ftype (function (fixnum) integer) %f))     (%f 10)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.21" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.21" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (flet ((%f (x &optional (y 1 y-p) (z 2 z-p))              (list x y (not (not y-p)) z (not (not z-p)))))     (values (%f 10) (%f 20 40) (%f 'a 'b 'c))))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.22" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.22" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (flet ((%f (x &optional (y 1 y-p) (z 2 z-p) &rest r)              (list x y (not (not y-p)) z (not (not z-p)) r)))     (values (%f 10) (%f 20 40) (%f 'a 'b 'c) (%f 'd 'e 'f 'g 'h))))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.23" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.23" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (flet ((%f (x &optional (y 1 y-p) (z 2 z-p) &rest r &key foo bar)              (list x y (not (not y-p)) z (not (not z-p)) r foo bar)))     (values (%f 10) (%f 20 40) (%f 'a 'b 'c)             (%f 'd 'e 'f :foo 'h)             (%f 'd 'e 'f :bar 'i) )))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.24" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.24" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (flet ((%f (x &optional (y 1 y-p) (z 2 z-p) &rest r &key foo bar                 &allow-other-keys)              (list x y (not (not y-p)) z (not (not z-p)) r foo bar)))     (values (%f 10) (%f 20 40) (%f 'a 'b 'c)             (%f 'd 'e 'f :foo 'h :whatever nil)             (%f 'd 'e 'f :bar 'i :illegal t :foo 'z) )))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.25" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.25" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (flet ((%f (x &optional (y 1 y-p) (z 2 z-p) &rest r &key foo bar)              (list x y (not (not y-p)) z (not (not z-p)) r foo bar)))     (values (%f 10) (%f 20 40) (%f 'a 'b 'c)             (%f 'd 'e 'f :foo 'h :whatever nil :allow-other-keys t)             (%f 'd 'e 'f :bar 'i :illegal t :foo 'z :allow-other-keys t) )))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.26" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.26" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (flet ((%f (x &optional (y 1 y-p) (z 2 z-p) &rest r &key foo bar)              (list x y (not (not y-p)) z (not (not z-p)) r foo bar)))     (values (%f 10) (%f 20 40) (%f 'a 'b 'c)             (%f 'd 'e 'f :foo 'h :allow-other-keys nil)             (%f 'd 'e 'f :bar 'i :allow-other-keys nil) )))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.27" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.27" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (flet ((%f (x &optional (y 1 y-p) (z 2 z-p) &rest r                 &key foo bar allow-other-keys)              (list x y (not (not y-p)) z (not (not z-p)) allow-other-keys                    r foo bar)))     (values (%f 10) (%f 20 40) (%f 'a 'b 'c)             (%f 'd 'e 'f :foo 'h :whatever nil :allow-other-keys 100)             (%f 'd 'e 'f :bar 'i :illegal t :foo 'z :allow-other-keys 200) )))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.28" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.28" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (flet ((%f (x &optional (y 1 y-p) (z 2 z-p) &rest r                 &key foo bar allow-other-keys &allow-other-keys)              (list x y (not (not y-p)) z (not (not z-p)) allow-other-keys                    r foo bar)))     (values (%f 10) (%f 20 40) (%f 'a 'b 'c)             (%f 'd 'e 'f :foo 'h :whatever nil :allow-other-keys nil :blah t)             (%f 'd 'e 'f :bar 'i :illegal t :foo 'z                 :allow-other-keys nil :zzz 10) )))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.29" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.29" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (flet ((%f (&key ((foo bar) nil)) bar))     (values (%f) (%f 'foo 10))))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.30" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.30" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (flet ((%f (&key ((:foo bar) nil)) bar))     (values (%f) (%f :foo 10))))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.31" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.31" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (flet ((%f (&key a b c) (list a b c)))     (%f :a 10 :b 20 :c 30 :a 40 :b 50 :c 60)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.32" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.32" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (flet ((%f (x y &aux (a (1+ x)) (b (+ x y a)) (c (list x y a b)))              c))     (%f 5 9)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.33" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.33" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (flet ((%f (x y &rest r &key foo bar &aux (c (list x y r foo bar)))              c))     (values      (%f 1 2)      (%f 1 2 :foo 'a)      (%f 1 2 :bar 'b)      (%f 1 2 :foo 'a :bar 'b)      (%f 1 2 :bar 'b :foo 'a))))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.34" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.34" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (let ((x 'bad))     (declare (special x))     (flet ((%f () x))       (flet ((%g (x)                  (declare (special x))                  (%f)))         (%g 'good)))))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.35" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.35" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (let ((x 'bad))     (declare (special x))     (flet ((%f () x))       (flet ((%g (&aux (x 'good))                  (declare (special x))                  (%f)))          (%g)))))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.36" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.36" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (let ((x 'bad))     (declare (special x))     (flet ((%f () x))       (flet ((%g (&rest x)                  (declare (special x))                  (%f)))          (%g 'good)))))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.37" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.37" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (let ((x 'bad))     (declare (special x))     (flet ((%f () x))       (flet ((%g (&key (x 'good))                  (declare (special x))                  (%f)))          (%g)))))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.38" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.38" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (let ((x 'bad))     (declare (special x))     (flet ((%f () x))       (flet ((%g (&key (x 'bad))                  (declare (special x))                  (%f)))          (%g :x 'good)))))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.39" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.39" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (let ((x 'good))     (declare (special x))     (flet ((%f () x))       (flet ((%g (&key (x 'bad))                  (%f)))          (%g :x 'worse)))))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.40" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.40" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (flet ((nil () 'a)) (nil)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.45" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.45" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (flet ((t () 'b)) (t)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.46" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.46" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (flet ((:foo () 'bar)) (:foo)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.47" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.47" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (flet ((:foo () 'bar)) (funcall #':foo)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.48" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.48" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (loop for s in *cl-non-function-macro-special-operator-symbols*         for form = `(ignore-errors (flet ((,s () 'a)) (,s)))         unless (eq (eval form) 'a)         collect s))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.49" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.49" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (loop for s in *cl-non-function-macro-special-operator-symbols*         for form = `(ignore-errors (flet ((,s () 'a))                                       (declare (ftype (function () symbol)                                                       ,s))                                       (,s)))         unless (eq (eval form) 'a)         collect s))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.50" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.50" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (loop for s in *cl-non-function-macro-special-operator-symbols*         for form = `(ignore-errors                      (flet (((setf ,s) (&rest args)                              (declare (ignore args))                              'a))                        (setf (,s) 10)))         unless (eq (eval form) 'a)         collect s))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.51" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.51" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (block done     (tagbody      (flet ((%f () (go 10) 10 (return-from done 'bad)))        (%f))      10      (return-from done 'good))))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.52" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.52" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (flet ((%f (&key (a 'wrong)) a)) (%f :a nil)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.53" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.53" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (flet ((%f (&key (a 'wrong a-p)) (list a (not a-p)))) (%f :a nil)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.54" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.54" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (flet ((%f (&key ((:a b) 'wrong)) b)) (%f :a nil)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.55" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.55" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (flet ((%f (&key ((:a b) 'wrong present?)) (list b (not present?)))) (%f :a nil)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.56" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.56" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (flet ((%f (&key) 'good))     (%f :allow-other-keys nil)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.57" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.57" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (flet ((%f (&key) 'good))     (%f :allow-other-keys t)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.58" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.58" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (flet ((%f (&key) 'good))     (%f :allow-other-keys t :a 1 :b 2)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.59" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.59" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (flet ((%f (&key &allow-other-keys) 'good))     (%f :a 1 :b 2)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.60" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.60" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (signals-error    (flet ((%f (&key) :bad)) (%f nil nil))    program-error))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.61" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.61" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (let ((x :bad))     (declare (special x))     (let ((x :good))       (flet ((%f (&optional (y x))                  (declare (special x))                  y))         (%f)))))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.62" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.62" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (let ((x :bad))     (declare (special x))     (let ((x :good))       (flet ((%f (&key (y x))                  (declare (special x))                  y))         (%f)))))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.63" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.63" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (let ((x :bad))     (declare (special x))     (let ((x :good))       (flet () (declare (special x)))       x)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.64" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.64" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (let ((x :bad))     (declare (special x))     (let ((x :good))       (flet ((%f () (declare (special x)))))       x)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.65" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.65" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (let ((x :bad))     (declare (special x))     (let ((x :good))       (flet ((%f () (declare (special x))))         x))))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.66" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.66" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (let ((x :bad))     (declare (special x))     (let ((x :good))       (flet ((%f (&aux (y x))                  (declare (special x))                  y))         (%f)))))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.67" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.67" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (let ((x :bad))     (declare (special x))     (let ((x :good))       (flet ((%f () x))         (declare (special x))         (%f)))))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.68" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.68" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (let ((*x* 0))     (declare (special *x*))     (flet ((%f (i)                #'(lambda (arg)                    (declare (ignore arg))                    (incf *x* i))))       (values        (mapcar (%f 1) '(a b c))        (mapcar (%f 2) '(a b c))))))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.69" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.69" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (macrolet ((%m (z) z))             (flet () (expand-in-current-env (%m :good)))))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.70" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.70" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (macrolet ((%m (z) z))             (flet ((%f () (expand-in-current-env (%m :good))))                   (%f))))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.71" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.71" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (flet ((flet.72 () :good))      (flet.72)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.72" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.72" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (flet ((flet.73 () :good))      (flet.73)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.73" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.73" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (define-compiler-macro flet.74 (&whole form)       :bad))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "flet.74" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "flet.74" c *jit-translate-err-count*)))
