;; auto-generated flet/labels battery
(defvar *fb0* 0)
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (labels ((%f () 1))     (%f)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.1" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.1" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (labels ((%f (x) x))     (%f 2)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.2" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.2" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (labels ((%f (&rest args) args))     (%f 'a 'b 'c)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.3" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.3" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (block %f     (labels ((%f (&optional (x (return-from %f :good)))                nil))       (%f)       :bad)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.4" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.4" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (block %f     (labels ((%f (&key (x (return-from %f :good)))                nil))       (%f)       :bad)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.4a" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.4a" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (labels ((%f () (return-from %f 15) 35))     (%f)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.5" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.5" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (block %f     (labels ((%f (&aux (x (return-from %f 10)))                20))       (%f)       :bad)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.6" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.6" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (labels ((%f (x n) (cond ((eql n 0) x)                            (t (%f (+ x n) (1- n))))))     (%f 0 10)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.7" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.7" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (labels ((%f (x &aux (b (%g x))) b)            (%g (y) (+ y y)))     (%f 10)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.7b" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.7b" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (labels ((%f (x &optional (b (%g x))) b)            (%g (y) (+ y y)))     (%f 10)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.7c" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.7c" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (labels ((%f (x &key (b (%g x))) b)            (%g (y) (+ y y)))     (%f 10)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.7d" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.7d" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (labels ((%f (&key a (b 0 b-p)) (values a b (not (not b-p)))))     (%f)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.8" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.8" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (labels ((%f (&key a (b 0 b-p)) (values a b (not (not b-p)))))     (%f :a 1)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.9" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.9" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (labels ((%f (&key a (b 0 b-p)) (values a b (not (not b-p)))))     (%f :b 2)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.10" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.10" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (labels ((%f (&key a (b 0 b-p)) (values a b (not (not b-p)))))     (%f :b 2 :a 3)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.11" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.11" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (signals-error    (labels ((%f (&key a (b 0 b-p)) (values a b (not (not b-p))))) (%f :c 4))    program-error))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.12" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.12" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (signals-error    (labels ((%f (&key a (b 0 b-p)) (values a b (not (not b-p))))) (%f :a))    program-error))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.13" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.13" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (signals-error (labels ((%f (a) a)) (%f))                  program-error))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.14" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.14" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (signals-error (labels ((%f (a) a)) (%f 1 2))                  program-error))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.15" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.15" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (signals-error (labels ((%f (&key a) a)) (%f '(foo)))                  program-error))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.16" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.16" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (labels (((setf %f) (x y) (setf (car y) x)))     (let ((z (list 1 2)))       (setf (%f z) 'a)       z)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.17" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.17" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (labels ((%f (x) (incf x) (+ x x)))     (%f 10)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.18" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.18" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (labels ((%f (a1 a2 a3 a4 a5 a6 a7 a8 a9 a10                 b1 b2 b3 b4 b5 b6 b7 b8 b9 b10                 c1 c2 c3 c4 c5 c6 c7 c8 c9 c10                 d1 d2 d3 d4 d5 d6 d7 d8 d9 d10                 e1 e2 e3 e4 e5 e6 e7 e8 e9 e10)                (+ a1 a2 a3 a4 a5 a6 a7 a8 a9 a10                   b1 b2 b3 b4 b5 b6 b7 b8 b9 b10                   c1 c2 c3 c4 c5 c6 c7 c8 c9 c10                   d1 d2 d3 d4 d5 d6 d7 d8 d9 d10                   e1 e2 e3 e4 e5 e6 e7 e8 e9 e10)))     (%f 1 2 3 4 5 6 7 8 9 10         11 12 13 14 15 16 17 18 19 20         21 22 23 24 25 26 27 28 29 30         31 32 33 34 35 36 37 38 39 40         41 42 43 44 45 46 47 48 49 50)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.19" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.19" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (let* ((n (min (1- lambda-parameters-limit) 1024))          (vars (loop repeat n collect (gensym))))     (eval      `(eqlt ,n             (labels ((%f ,vars (+ ,@ vars)))               (%f ,@(loop for e in vars collect 1)))))))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.20" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.20" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (labels ((%f (x)              (declare (type fixnum x))              "Add one to the fixnum x."              (1+ x)))     (declare (ftype (function (fixnum) integer) %f))     (%f 10)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.21" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.21" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (labels ((:foo () 10)            (:bar () (1+ (:foo))))     (:bar)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.22" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.22" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (labels ((:foo () 10)            (:bar () (1+ (funcall #':foo))))     (funcall #':bar)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.23" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.23" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (loop for s in *cl-non-function-macro-special-operator-symbols*         for form = `(ignore-errors (labels ((,s (x) (foo (1- x)))                                             (foo (y)                                                  (if (<= y 0) 'a                                                    (,s (1- y)))))                                      (,s 10)))         unless (eq (eval form) 'a)         collect s))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.24" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.24" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (loop for s in *cl-non-function-macro-special-operator-symbols*         for form = `(ignore-errors                      (labels ((,s (x) (foo (1- x)))                               (foo (y)                                    (if (<= y 0) 'a                                      (,s (1- y)))))                        (declare (ftype (function (integer) symbol)                                        foo ,s))                        (,s 10)))         unless (eq (eval form) 'a)         collect s))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.25" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.25" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (loop for s in *cl-non-function-macro-special-operator-symbols*         for form = `(ignore-errors                      (labels (((setf ,s) (&rest args)                                (declare (ignore args))                                'a))                        (setf (,s) 10)))         unless (eq (eval form) 'a)         collect s))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.26" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.26" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (block done     (tagbody      (labels ((%f () (go 10) 10 (return-from done 'bad)))        (%f))      10      (return-from done 'good))))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.27" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.27" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (labels ((%f (&key (a 'wrong)) a)) (%f :a nil)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.28" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.28" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (labels ((%f (&key (a 'wrong a-p)) (list a (not a-p)))) (%f :a nil)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.29" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.29" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (labels ((%f (&key ((:a b) 'wrong)) b)) (%f :a nil)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.30" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.30" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (labels ((%f (&key ((:a b) 'wrong present?)) (list b (not present?))))     (%f :a nil)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.31" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.31" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (labels ((%f (&key) 'good))     (%f :allow-other-keys nil)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.32" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.32" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (labels ((%f (&key) 'good))     (%f :allow-other-keys t)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.33" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.33" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (labels ((%f (&key) 'good))     (%f :allow-other-keys t :a 1 :b 2)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.34" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.34" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (labels ((%f (&key &allow-other-keys) 'good))     (%f :a 1 :b 2)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.35" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.35" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (signals-error    (labels ((%f (&key) :bad)) (%f nil nil))    program-error))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.36" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.36" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (labels ((f () 'foo))     (eqt #'f #'f)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.37" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.37" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (labels ((f () 'foo))     (destructuring-bind (x y) (loop repeat 2 collect #'f) (eqlt x y))))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.38" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.38" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (labels ((f () #'f))     (eqlt (f) #'f)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.39" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.39" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (let ((x :bad))     (declare (special x))     (let ((x :good))       (labels ((%f (&optional (y x))                    (declare (special x))                    y))         (%f)))))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.41" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.41" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (let ((x :bad))     (declare (special x))     (let ((x :good))       (labels ((%f (&key (y x))                    (declare (special x))                    y))         (%f)))))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.42" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.42" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (let ((x :bad))     (declare (special x))     (let ((x :good))       (labels () (declare (special x)))       x)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.43" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.43" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (let ((x :bad))     (declare (special x))     (let ((x :good))       (labels ((%f () (declare (special x)))))       x)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.44" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.44" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (let ((x :bad))     (declare (special x))     (let ((x :good))       (labels ((%f () (declare (special x))))         x))))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.45" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.45" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (let ((x :bad))     (declare (special x))     (let ((x :good))       (labels ((%f (&aux (y x))                    (declare (special x))                    y))         (%f)))))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.46" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.46" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (let ((x :bad))     (declare (special x))     (let ((x :good))       (labels ((%f () x))         (declare (special x))         (%f)))))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.47" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.47" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (macrolet ((%m (z) z))             (labels () (expand-in-current-env (%m :good)))))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.48" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.48" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (macrolet ((%m (z) z))             (labels ((%f () (expand-in-current-env (%m :good))))                     (%f))))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.49" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.49" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (labels ((labels.50 () :good))      (labels.50)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.50" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.50" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (labels ((labels.51 () :good))       (labels.51)))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.51" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.51" c *jit-translate-err-count*)))
(setq *fb0* (or *jit-fallback-count* 0))
(handler-case (let ((v (progn (define-compiler-macro labels.52 (&whole form)       :bad))))
  (format t "~A val=~S fbdelta=~A terr=~A~%" "labels.52" v (- (or *jit-fallback-count* 0) *fb0*) *jit-translate-err-count*))
  (t (c) (format t "~A CRASH ~A terr=~A~%" "labels.52" c *jit-translate-err-count*)))
