;;; Repro: replicate %eval2-compile-tuple's compile in host SBCL, then
;;; translate the resulting bytecode with *x64-jit-mode* t and show the
;;; exact opcode/operand that triggers `Unknown register: 0`.
(load "lib/load-mvm.lisp")
(in-package :modus.mvm)

(setq *mvm-emit-halves* t)
(defun compile-tuple (forms)
  (unless (and *opcode-table* (> (hash-table-count *opcode-table*) 0))
    (setq *opcode-table* (make-hash-table :test 'eql))
    (%populate-opcode-table))
  (let ((*functions* (make-hash-table :test 'equal))
        (*function-table* nil) (*constant-table* nil) (*label-counter* 0)
        (*unresolved-calls* (make-hash-table :test 'equal))
        (*macro-table* (make-hash-table :test 'eql))
        (*globals* (make-hash-table :test 'eql))
        (*constants* (make-hash-table :test 'eql))
        (*loop-exit-label* nil) (*block-labels* nil) (*tagbody-tags* nil)
        (*pending-flet-ir* nil) (*init-thunk-names* nil)
        (all-ir nil) (buf nil) (global-offset 0) (entry nil)
        (rt-table (make-hash-table)) (rt-next #x40000000))
    (register-mvm-bootstrap-macros)
    (let* ((rforms (reverse forms)) (last-form (car rforms))
           (expr last-form) (defs (reverse (cdr rforms)))
           (toplevel (append defs (list (list 'defun '%eval2-thunk nil expr)))))
      (dolist (f toplevel)
        (let ((result (mvm-compile-toplevel f)))
          (cond ((null result) nil)
                ((and (consp result) (eq (car result) :multi-result))
                 (dolist (sub (cdr result))
                   (when (and (car sub) (cdr sub))
                     (setq all-ir (cons (cons (car sub) (cdr sub)) all-ir)))))
                (t (when (and (car result) (cdr result))
                     (setq all-ir (cons (cons (car result) (cdr result)) all-ir)))))))
      (dolist (pend *pending-flet-ir*)
        (when (and (consp pend) (car pend) (cdr pend))
          (setq all-ir (cons pend all-ir))))
      (setq all-ir (reverse all-ir))
      (setq buf (make-mvm-buffer :bytes (make-array 65536)))
      (dolist (e all-ir)
        (let* ((info (car e)) (ir (cdr e))
               (fn-size (let ((s 0)) (dolist (insn ir) (setq s (+ s (ir-instruction-size insn)))) s)))
          (setf (function-info-bytecode-offset info) global-offset)
          (setf (function-info-bytecode-length info) fn-size)
          (setf (gethash (function-info-name info) *functions*) info)
          (setq global-offset (+ global-offset fn-size))))
      (dolist (e all-ir)
        (dolist (insn (cdr e))
          (let ((name (cond ((eq (car insn) :call) (cadr insn))
                            ((eq (car insn) :li-func) (caddr insn)) (t nil))))
            (when (and name (stringp name) (not (gethash name *functions*)))
              (let ((info (make-function-info :name name :bytecode-offset rt-next :bytecode-length 0)))
                (setf (gethash name *functions*) info)
                (setf (gethash rt-next rt-table) name)
                (setq rt-next (+ rt-next 1)))))))
      (dolist (e all-ir)
        (let* ((ir (cdr e)) (lp (compute-label-positions ir)))
          (emit-bytecode-for-ir buf ir lp)))
      (dolist (e all-ir)
        (when (string-equal (string (function-info-name (car e))) "%EVAL2-THUNK")
          (setq entry (function-info-bytecode-offset (car e)))))
      (let ((bc (mvm-buffer-used-bytes buf)) (ft-list nil))
        (dolist (e all-ir)
          (let ((nm (string (function-info-name (car e))))
                (off (function-info-bytecode-offset (car e)))
                (len (function-info-bytecode-length (car e))))
            (setq ft-list (cons (list nm off len) ft-list))))
        (list bc entry (reverse ft-list) rt-table)))))

(defun try-form (label form)
  (format t "~&=== ~A : ~S~%" label form)
  (let* ((tuple (compile-tuple (list form)))
         (bc (car tuple)) (ft-list (caddr tuple))
         (rt-n (hash-table-count (cadddr tuple))))
    (format t "  compiled: bc-len=~D rt=~D ft=~S~%" (length bc) rt-n ft-list)
    (let ((modus.mvm.x64::*x64-jit-mode* t))
      (handler-case
          (multiple-value-bind (nbuf fn-map)
              (modus.mvm.x64::translate-mvm-to-x64 bc ft-list)
            (declare (ignore fn-map))
            (format t "  JIT translate OK: native-len=~D~%"
                    (modus.mvm.x64::code-buffer-position nbuf)))
        (error (c)
          (format t "  JIT translate ERROR: ~A~%" c)
          (sb-debug:print-backtrace :count 30 :stream *standard-output*))))))

(try-form "flet.62" '(let ((x :bad)) (declare (special x)) (let ((x :good)) (flet ((%f (&optional (y x)) (declare (special x)) y)) (%f)))))
(try-form "flet.63" '(let ((x :bad)) (declare (special x)) (let ((x :good)) (flet ((%f (&optional (y x)) x)) (declare (special x)) (%f)))))
(sb-ext:exit)

