(defmacro once-only (specs &body forms)
  (let ((gensyms (loop for s in specs collect (gensym "OO")))
        (names-and-forms (mapcar (lambda (spec) (if (consp spec) (cons (car spec) (cadr spec)) (cons spec spec))) specs)))
    `(let ,(mapcar (lambda (g n) (list g `(gensym ,(string (car n))))) gensyms names-and-forms)
       `(let (,,@(mapcar (lambda (g n) ``(,,g ,,(cdr n))) gensyms names-and-forms))
          ,(let ,(mapcar (lambda (n g) (list (car n) g)) names-and-forms gensyms) ,@forms)))))
(defmacro with-unique-names (bindings &body body)
  `(let ,(mapcar (lambda (b) (let ((s (if (consp b) (car b) b))) `(,s (gensym ,(string s))))) bindings) ,@body))
(defmacro ensure-gethash (key hash-table &optional default)
  (once-only (key hash-table)
    (with-unique-names (value presentp)
      `(multiple-value-bind (,value ,presentp) (gethash ,key ,hash-table)
         (if ,presentp (values ,value ,presentp)
             (values (setf (gethash ,key ,hash-table) ,default) nil))))))
(format t "EG-EXPAND => ~S~%" (macroexpand-1 '(ensure-gethash k tab 42)))
(let ((h (make-hash-table)))
  (format t "EG miss => ~S (want 42)~%" (ensure-gethash 'a h 42))
  (format t "EG hit  => ~S (want 42)~%" (ensure-gethash 'a h 99))
  (format t "EG table => ~S (want 42)~%" (gethash 'a h)))
