(defmacro once-only (specs &body forms)
  (let ((gensyms (loop for s in specs collect (gensym "OO")))
        (names-and-forms (mapcar (lambda (spec) (if (consp spec) (cons (car spec) (cadr spec)) (cons spec spec))) specs)))
    `(let ,(mapcar (lambda (g n) (list g `(gensym ,(string (car n))))) gensyms names-and-forms)
       `(let (,,@(mapcar (lambda (g n) ``(,,g ,,(cdr n))) gensyms names-and-forms))
          ,(let ,(mapcar (lambda (n g) (list (car n) g)) names-and-forms gensyms) ,@forms)))))
(defmacro cons1 (x) (once-only (x) `(cons ,x ,x)))
(let ((y 0)) (format t "CONS1 => ~S  (want (1 . 1))~%" (cons1 (incf y))))
(defmacro succ2 (expr) (once-only ((var `(1+ ,expr))) `(list ',expr ,var ,var)))
(let ((y 10)) (format t "SUCC2 => ~S  (want ((INCF Y) 12 12))~%" (succ2 (incf y))))
(let ((a 1)(b 2)) (macrolet ((m (x y) (once-only (x y) `(list ,x ,y ,x ,y))))
  (format t "OO2 => ~S  (want (2 3 2 3))~%" (m (incf a)(incf b)))))
;; backquote regressions
(let ((a 2)) (format t "R1 ~S (want (1 2 3))~%" `(1 ,a 3)))
(let ((a '(2 3))) (format t "R2 ~S (want (1 2 3 4))~%" `(1 ,@a 4)))
(let ((a 5)) (format t "R3 ~S (want (X . 5))~%" `(x . ,a)))
(let ((v 9)) (format t "R4 ~S~%" `(outer `(inner ,,v))))
