;;; Reader bisect probe: read a file form-by-form, report position at failure.
(defun rd-slurp (path)
  (tar-bytes-to-string (%it-slurp-bytes path)))

(defun rd-probe (path)
  (let* ((src (rd-slurp path))
         (n (length src))
         (s (make-string-input-stream src))
         (i 0)
         (last 0))
    (princ "FILE ") (princ path) (princ " len=") (princ n) (terpri)
    (loop
      (let* ((pos (handler-case (file-position s) (t (c) -1)))
             (r (handler-case (read s nil :rd-eof)
                  (t (c) (list :RD-ERR (handler-case (type-of c) (t (c2) :UNKNOWN)))))))
        (when (eq r :rd-eof)
          (princ "  OK-EOF forms=") (princ i) (terpri) (finish-output) (return :ok))
        (when (and (consp r) (eq (car r) :RD-ERR))
          (let ((p2 (handler-case (file-position s) (t (c) -1))))
            (princ "  FAIL form#") (princ i)
            (princ " startpos=") (princ pos)
            (princ " endpos=") (princ p2)
            (princ " cond=") (princ (cadr r)) (terpri)
            (princ "  CTX<<<")
            (princ (subseq src (max 0 (- pos 0)) (min n (+ pos 260))))
            (princ ">>>") (terpri) (finish-output)
            (return :fail)))
        (setq last pos)
        (setq i (+ i 1))))))
