(require :sb-rt)
(require :asdf)
(push #p"/home/claude/quicklisp/dists/quicklisp/software/alexandria-20241012-git/" asdf:*central-registry*)
(handler-bind ((warning #'muffle-warning)) (asdf:load-system :alexandria))
(handler-bind ((warning #'muffle-warning))
  (load "/home/claude/quicklisp/dists/quicklisp/software/alexandria-20241012-git/alexandria-2/tests.lisp"))
(format t "~&ORACLE2-REGISTERED=~a~%" (length (cdr sb-rt::*entries*)))
(format t "~&ORACLE2-RESULT=~a~%" (sb-rt:do-tests))
(sb-ext:quit)
