(require :sb-rt)
(require :asdf)
(push #p"/home/claude/quicklisp/dists/quicklisp/software/alexandria-20241012-git/" asdf:*central-registry*)
(handler-bind ((warning #'muffle-warning))
  (asdf:load-system :alexandria))
(handler-bind ((warning #'muffle-warning))
  (load "/home/claude/quicklisp/dists/quicklisp/software/alexandria-20241012-git/alexandria-1/tests.lisp"))
(format t "~&ORACLE-REGISTERED=~a~%" (length sb-rt::*entries*))
(let ((fails (sb-rt:do-tests)))
  (format t "~&ORACLE-FAILS=~a~%" fails))
(sb-ext:quit)
