(defun say (k v) (princ (concatenate 'string k "=" (princ-to-string v))) (terpri) (finish-output))
(defun slurp (p) (tar-bytes-to-string (%it-slurp-bytes p)))
(say "A0.start" (package-name *package*))
(say "A0.npkgs0" (length (list-all-packages)))
(say "A1.eval" (handler-case (%it-eval-source (slurp "/home/claude/ws-loader/vendor/asdf/asdf.lisp") "asdf")
                (t (c) (list :ERR (handler-case (type-of c) (t (c2) :UNKNOWN))))))
(say "A2.after-pkg" (package-name *package*))
(say "A3.pkg-asdf" (if (find-package "ASDF") 1 0))
(say "A4.pkg-uiop" (if (find-package "UIOP") 1 0))
(say "A5.npkgs" (length (list-all-packages)))
(say "A6.defsystem" (handler-case (if (fboundp (read-from-string "asdf::defsystem")) 1 0) (t (c) (list :ERR (type-of c)))))
(say "A7.load-system" (handler-case (if (fboundp (read-from-string "asdf::load-system")) 1 0) (t (c) (list :ERR (type-of c)))))
(say "A8.find-system" (handler-case (if (fboundp (read-from-string "asdf::find-system")) 1 0) (t (c) (list :ERR (type-of c)))))
(say "A9.class-system" (handler-case (if (find-class (read-from-string "asdf::system") nil) 1 0) (t (c) (list :ERR (type-of c)))))
(say "A10.feature-asdf3" (if (member :asdf3.1 *features*) 1 0))
(say "LF-END" "asdf2")
