(defun say (k v) (princ (concatenate 'string k "=" (princ-to-string v))) (terpri) (finish-output))
(say "A0.start" (package-name *package*))
(say "A1.load" (handler-case (progn (load "/home/claude/ws-loader/vendor/asdf/asdf.lisp") :LOADED)
                (t (c) (list :ERR (handler-case (type-of c) (t (c2) :UNKNOWN))))))
(say "A2.after-pkg" (package-name *package*))
(say "A3.pkg-asdf" (if (find-package "ASDF") 1 0))
(say "A4.pkg-uiop" (if (find-package "UIOP") 1 0))
(say "A5.npkgs" (length (list-all-packages)))
(say "A6.defsystem" (handler-case (if (fboundp (read-from-string "asdf::defsystem")) 1 0) (t (c) (list :ERR (type-of c)))))
(say "A7.load-system" (handler-case (if (fboundp (read-from-string "asdf:load-system")) 1 0) (t (c) (list :ERR (type-of c)))))
(say "A8.feature-asdf3" (if (member :asdf3.1 *features*) 1 0))
(say "LF-END" "asdf")
