(defun say (k v) (princ (concatenate 'string k "=" (princ-to-string v))) (terpri) (finish-output))
(defun pr (k src)
  (say k (handler-case (eval (read-from-string src))
           (t (c) (list :ERR (handler-case (type-of c) (t (c2) :UNKNOWN)))))))
(say "E.features" *features*)
(pr "E.pkgs" "(list (if (find-package \"ASDF\") 1 0) (if (find-package \"UIOP\") 1 0) (if (find-package \"ASDF-USER\") 1 0))")
(pr "E.ver" "(asdf:asdf-version)")
(pr "E.vle1" "(asdf:version<= \"3.1\" (asdf:asdf-version))")
(pr "E.vle2" "(list (uiop:version<= \"3.1\" \"3.1\") (uiop:version< \"3.1\" \"3.1.2\") (uiop:version< \"3.3.7\" \"3.1\"))")
(pr "E.same-sym" "(eq 'asdf:version<= 'uiop:version<=)")
(pr "E.parse" "(uiop:parse-version \"3.3.7\")")
(pr "E.guard" "(read-from-string \"#.(unless (or #+asdf3.1 (version<= \\\"3.1\\\" (asdf-version))) (error \\\"You need ASDF >= 3.1\\\"))\")")
(pr "E.guard-asdfuser" "(let ((p *package*)) (setq *package* (find-package \"ASDF-USER\")) (let ((r (handler-case (read-from-string \"#.(unless (or #+asdf3.1 (version<= \\\"3.1\\\" (asdf-version))) (error \\\"boom\\\")) \") (t (c) (list :ERR (type-of c)))))) (setq *package* p) r))")
(pr "E.classes" "(list (if (find-class 'asdf:system nil) 1 0) (if (find-class 'asdf:cl-source-file nil) 1 0))")
(pr "E.regs0" "(asdf:registered-systems)")
(pr "E.find-miss" "(handler-case (asdf:find-system \"no-such-system-xyz\") (asdf:missing-component (c) :MISSING) (t (c) (list :OTHER (type-of c))))")
(pr "E.find-miss-nil" "(asdf:find-system \"no-such-system-xyz\" nil)")
(pr "E.load-miss" "(handler-case (asdf:load-system \"no-such-system-xyz\") (asdf:missing-component (c) :MISSING) (t (c) (list :OTHER (type-of c))))")
(pr "E.perform" "(handler-case (asdf:perform 'asdf:compile-op 1) (error (c) :SIGNALS))")
(pr "E.primary" "(list (asdf:primary-system-name \"foo/test\") (asdf:primary-system-name :Foo))")
(pr "E.scl" "(multiple-value-list (find-symbol \"BOOLEAN\" \"SCL\"))")
(pr "E.scl-eq" "(eq (find-symbol \"BOOLEAN\" \"SCL\") (find-symbol \"BOOLEAN\" \"COMMON-LISP\"))")
(pr "E.hook" "(if *it-register-hook* 1 0)")
;; real install through Modus's loader, then ASDF-visible
(pr "E.install" "(install-tarball \"/home/claude/lf/tars/split-sequence.tar\" \"split-sequence\")")
(pr "E.reg-after" "(asdf:registered-systems)")
(pr "E.loadedp" "(asdf:component-loaded-p (asdf:find-system \"split-sequence\"))")
(pr "E.eqsys" "(eq (asdf:find-system \"split-sequence\") (asdf:find-system \"split-sequence\"))")
(pr "E.cname" "(asdf:component-name (asdf:find-system \"split-sequence\"))")
(pr "E.loadsys-again" "(asdf:load-system \"split-sequence\")")
(pr "E.split" "(funcall (read-from-string \"split-sequence:split-sequence\") #\\, \"a,b,c\")")
;; central-registry directory loading
(pr "E.cr" "(progn (setq asdf:*central-registry* (list \"/home/claude/quicklisp/dists/quicklisp/software/alexandria-20241012-git/\")) (asdf:component-name (asdf:find-system \"alexandria\")))")
(pr "E.cr-loaded0" "(asdf:component-loaded-p (asdf:find-system \"alexandria\"))")
(pr "E.cr-load" "(asdf:load-system \"alexandria\")")
(pr "E.cr-probe" "(funcall (read-from-string \"alexandria:flatten\") (list 1 (list 2 3)))")
(pr "E.srcfile" "(asdf:system-source-file (asdf:find-system \"alexandria\"))")
(pr "E.srcdir" "(asdf:system-source-directory (asdf:find-system \"alexandria\"))")
(pr "E.deps" "(asdf:system-depends-on (asdf:find-system \"alexandria\"))")
(pr "E.clear" "(list (asdf:clear-system \"alexandria\") (asdf:registered-system \"alexandria\"))")
(say "DONE" 1)
