(defun say (k v) (princ (concatenate 'string k "=" (princ-to-string v))) (terpri) (finish-output))
(say "FEATURES" *features*)
(say "F.genera" (if (%it-feature-true-p :genera) 1 0))
(say "F.sbcl" (if (%it-feature-true-p :sbcl) 1 0))
(say "F.not-acl" (if (%it-feature-true-p (list :not :use-acl-regexp2-engine)) 1 0))
(say "F.or" (if (%it-feature-true-p (list :or :sbcl :abcl)) 1 0))
(say "F.nil" (if (%it-feature-true-p nil) 1 0))
(say "D.pathname" (%it-dir-prefix "src"))
(say "LF-END" "feat")
