(defun say (k v) (princ (concatenate 'string k "=" (princ-to-string v))) (terpri) (finish-output))
(defun lf-load-file (path)
  (let ((p *package*) (r nil))
    (setq r (handler-case (%it-eval-source (tar-bytes-to-string (%it-slurp-bytes path)) path)
              (t (c) (list :FILE-ABORT (handler-case (type-of c) (t (c2) :UNKNOWN))))))
    (setq *package* p)
    r))
(defun pr (k src)
  (say k (handler-case (eval (read-from-string src))
           (t (c) (list :ERR (handler-case (type-of c) (t (c2) :UNKNOWN)))))))
(defvar *q* "/home/claude/quicklisp/dists/quicklisp/software/")
(say "X.f1" (lf-load-file (concatenate 'string *q* "mgl-pax-20260101-git/autoload/package.lisp")))
(say "X.f2" (lf-load-file (concatenate 'string *q* "mgl-pax-20260101-git/autoload/autoload.lisp")))
(say "X.f3" (lf-load-file (concatenate 'string *q* "mgl-pax-20260101-git/src/bootstrap/package.lisp")))
(say "X.f4" (lf-load-file (concatenate 'string *q* "mgl-pax-20260101-git/src/bootstrap/basics.lisp")))
(say "X.f5" (lf-load-file (concatenate 'string *q* "mgl-pax-20260101-git/src/bootstrap/pax-world.lisp")))
(pr "X.paxpkg" "(if (find-package \"MGL-PAX\") 1 0)")
(pr "X.pax-nick" "(if (find-package \"PAX\") 1 0)")
(pr "X.defsection" "(if (macro-function (read-from-string \"pax:defsection\")) 1 0)")
(say "X.n1" (lf-load-file (concatenate 'string *q* "named-readtables-20260101-git/src/package.lisp")))
(say "X.n2" (lf-load-file (concatenate 'string *q* "named-readtables-20260101-git/src/utils.lisp")))
(say "X.n3" (lf-load-file (concatenate 'string *q* "named-readtables-20260101-git/src/define-api.lisp")))
(say "X.n4" (lf-load-file (concatenate 'string *q* "named-readtables-20260101-git/src/cruft.lisp")))
(say "X.n5" (lf-load-file (concatenate 'string *q* "named-readtables-20260101-git/src/named-readtables.lisp")))
(say "X.n6" (lf-load-file (concatenate 'string *q* "named-readtables-20260101-git/src/doc.lisp")))
(pr "X.nrt" "(if (find-package \"NAMED-READTABLES\") 1 0)")
(pr "X.defrt" "(progn (eval (read-from-string \"(named-readtables:defreadtable lf-rt (:merge :standard))\")) (if (funcall (read-from-string \"named-readtables:find-readtable\") (quote lf-rt)) 1 0))")
(say "DONE" 1)
