(defclass k9 () ((a :initarg :a)))
(%register-clos-default-initargs 'k9 (list (cons :a (lambda () 90))))
(defun try-let ()
  (let ((*clos-applying-defaults* t))
    (let ((i (%make-instance 'k9))) (%shared-init-default-spread (list i t))
      (handler-case (slot-value i 'a) (error (c) :ERR)))))
(defun try-setq ()
  (setq *clos-applying-defaults* t)
  (let ((i (%make-instance 'k9))) (%shared-init-default-spread (list i t))
    (let ((r (handler-case (slot-value i 'a) (error (c) :ERR))))
      (setq *clos-applying-defaults* nil) r)))
(format t "TRY-LET:  ~S~%" (try-let))
(format t "TRY-SETQ: ~S~%" (try-setq))
