;;;; lib/cbor.lisp -- CBOR (RFC 8949), the subset the Nitro Security Module speaks.
;;;;
;;;; An NSM request is a CBOR map; the attestation document comes back as a
;;;; COSE_Sign1 (a tagged 4-element array) whose payload is another CBOR map.
;;;; Encoder and decoder over (unsigned-byte 8) vectors.  Values: integers (major
;;;; 0/1), byte strings (2) as (unsigned-byte 8) vectors, text strings (3) as Lisp
;;;; strings, arrays (4) as lists, maps (5) as alists of (key . value) in wire
;;;; order, tags (6) as (:tag N . item), and the simple values false/true/null
;;;; (7) as :false / :true / :null.  Indefinite lengths are not emitted and are
;;;; rejected on decode (the NSM never sends them).  Encoding is canonical in the
;;;; sense RFC 8949 4.2.1 asks for lengths: the shortest form, which is what the
;;;; NSM and every verifier expect.

(defun %cbor-u8vec (n) (make-array n :element-type '(unsigned-byte 8)))

;;; ---- encoder: an output buffer that grows -------------------------------
(defun %cbor-out () (cons (%cbor-u8vec 256) 0))     ; (vector . fill)
(defun %cbor-put (out b)
  (let ((v (car out)) (n (cdr out)))
    (when (>= n (length v))
      (let ((w (%cbor-u8vec (* 2 (length v)))))
        (dotimes (i n) (setf (aref w i) (aref v i)))
        (setf (car out) w) (setq v w)))
    (setf (aref v n) (logand b 255))
    (setf (cdr out) (+ n 1))))
(defun %cbor-head (out major n)
  "Major type + argument N in the shortest form."
  (let ((m (ash major 5)))
    (cond ((< n 24) (%cbor-put out (+ m n)))
          ((< n 256) (%cbor-put out (+ m 24)) (%cbor-put out n))
          ((< n 65536) (%cbor-put out (+ m 25)) (%cbor-put out (ash n -8)) (%cbor-put out n))
          ((< n 4294967296) (%cbor-put out (+ m 26))
           (%cbor-put out (ash n -24)) (%cbor-put out (ash n -16)) (%cbor-put out (ash n -8)) (%cbor-put out n))
          (t (%cbor-put out (+ m 27))
             (dotimes (i 8) (%cbor-put out (ash n (- (* 8 (- 7 i))))))))))
(defun %cbor-encode-into (out x)
  (cond ((eq x :false) (%cbor-put out #xF4))
        ((eq x :true)  (%cbor-put out #xF5))
        ((eq x :null)  (%cbor-put out #xF6))
        ((integerp x) (if (>= x 0) (%cbor-head out 0 x) (%cbor-head out 1 (- -1 x))))
        ((stringp x)
         (let ((bytes (%cbor-utf8 x)))
           (%cbor-head out 3 (length bytes))
           (dotimes (i (length bytes)) (%cbor-put out (aref bytes i)))))
        ((and (vectorp x) (not (stringp x)))
         (%cbor-head out 2 (length x))
         (dotimes (i (length x)) (%cbor-put out (aref x i))))
        ((and (consp x) (eq (car x) :tag))
         (%cbor-head out 6 (cadr x)) (%cbor-encode-into out (cddr x)))
        ((and (consp x) (eq (car x) :map))
         (%cbor-head out 5 (length (cdr x)))
         (dolist (kv (cdr x)) (%cbor-encode-into out (car kv)) (%cbor-encode-into out (cdr kv))))
        ((listp x)
         (%cbor-head out 4 (length x))
         (dolist (e x) (%cbor-encode-into out e)))
        (t (error "cbor-encode: cannot encode ~S" x))))
(defun cbor-encode (x)
  "X -> a fresh (unsigned-byte 8) vector.  Maps are written (:map (k . v) ...),
   tags (:tag N . item), simple values :false :true :null."
  (let ((out (%cbor-out)))
    (%cbor-encode-into out x)
    (let ((v (%cbor-u8vec (cdr out))))
      (dotimes (i (cdr out) v) (setf (aref v i) (aref (car out) i))))))
(defun %cbor-utf8 (s)
  (let ((n 0))
    (dotimes (i (length s)) (let ((c (char-code (char s i)))) (incf n (cond ((< c #x80) 1) ((< c #x800) 2) ((< c #x10000) 3) (t 4)))))
    (let ((v (%cbor-u8vec n)) (j 0))
      (dotimes (i (length s) v)
        (let ((c (char-code (char s i))))
          (cond ((< c #x80) (setf (aref v j) c) (incf j))
                ((< c #x800) (setf (aref v j) (logior #xC0 (ash c -6)) (aref v (+ j 1)) (logior #x80 (logand c #x3F))) (incf j 2))
                ((< c #x10000) (setf (aref v j) (logior #xE0 (ash c -12)) (aref v (+ j 1)) (logior #x80 (logand (ash c -6) #x3F))
                                     (aref v (+ j 2)) (logior #x80 (logand c #x3F))) (incf j 3))
                (t (setf (aref v j) (logior #xF0 (ash c -18)) (aref v (+ j 1)) (logior #x80 (logand (ash c -12) #x3F))
                         (aref v (+ j 2)) (logior #x80 (logand (ash c -6) #x3F)) (aref v (+ j 3)) (logior #x80 (logand c #x3F))) (incf j 4))))))))

;;; ---- decoder -------------------------------------------------------------
;;; A cursor is (vector . position); every reader advances it.
(defun %cbor-byte (cur)
  (let ((v (car cur)) (p (cdr cur)))
    (when (>= p (length v)) (error "cbor-decode: truncated at ~D" p))
    (setf (cdr cur) (+ p 1))
    (aref v p)))
(defun %cbor-arg (cur info)
  (cond ((< info 24) info)
        ((= info 24) (%cbor-byte cur))
        ((= info 25) (let ((a (%cbor-byte cur))) (+ (ash a 8) (%cbor-byte cur))))
        ((= info 26) (let ((n 0)) (dotimes (i 4 n) (setq n (+ (ash n 8) (%cbor-byte cur))))))
        ((= info 27) (let ((n 0)) (dotimes (i 8 n) (setq n (+ (ash n 8) (%cbor-byte cur))))))
        ((= info 31) (error "cbor-decode: indefinite length not supported"))
        (t (error "cbor-decode: reserved additional info ~D" info))))
(defun %cbor-bytes (cur n)
  (let ((v (%cbor-u8vec n)))
    (dotimes (i n v) (setf (aref v i) (%cbor-byte cur)))))
(defun %cbor-utf8-decode (bytes)
  (let ((chars nil) (i 0) (n (length bytes)))
    (loop
      (when (>= i n) (return))
      (let ((b (aref bytes i)))
        (cond ((< b #x80) (push (code-char b) chars) (incf i))
              ((< b #xE0) (push (code-char (logior (ash (logand b #x1F) 6) (logand (aref bytes (+ i 1)) #x3F))) chars) (incf i 2))
              ((< b #xF0) (push (code-char (logior (ash (logand b #x0F) 12) (ash (logand (aref bytes (+ i 1)) #x3F) 6)
                                                    (logand (aref bytes (+ i 2)) #x3F))) chars) (incf i 3))
              (t (push (code-char (logior (ash (logand b #x07) 18) (ash (logand (aref bytes (+ i 1)) #x3F) 12)
                                           (ash (logand (aref bytes (+ i 2)) #x3F) 6) (logand (aref bytes (+ i 3)) #x3F))) chars) (incf i 4)))))
    (coerce (nreverse chars) 'string)))
(defun %cbor-decode-item (cur)
  (let* ((b (%cbor-byte cur)) (major (ash b -5)) (info (logand b 31)))
    (cond ((= major 0) (%cbor-arg cur info))
          ((= major 1) (- -1 (%cbor-arg cur info)))
          ((= major 2) (%cbor-bytes cur (%cbor-arg cur info)))
          ((= major 3) (%cbor-utf8-decode (%cbor-bytes cur (%cbor-arg cur info))))
          ((= major 4) (let ((n (%cbor-arg cur info)) (items nil))
                         (dotimes (i n) (push (%cbor-decode-item cur) items))
                         (nreverse items)))
          ((= major 5) (let ((n (%cbor-arg cur info)) (kvs nil))
                         (dotimes (i n) (let ((k (%cbor-decode-item cur))) (push (cons k (%cbor-decode-item cur)) kvs)))
                         (cons :map (nreverse kvs))))
          ((= major 6) (let ((tag (%cbor-arg cur info))) (cons :tag (cons tag (%cbor-decode-item cur)))))
          (t (cond ((= info 20) :false) ((= info 21) :true) ((= info 22) :null)
                   ((= info 23) :undefined)
                   ((= info 24) (%cbor-byte cur) :simple)
                   (t (error "cbor-decode: unsupported simple/float ~D" info)))))))
(defun cbor-decode (bytes &optional (start 0))
  "Decode ONE item from BYTES at START -> (values item next-position)."
  (let ((cur (cons bytes start)))
    (let ((item (%cbor-decode-item cur)))
      (values item (cdr cur)))))
(defun cbor-map-get (map key)
  "MAP is a decoded (:map ...); KEY compared with EQUAL (strings, integers)."
  (cdr (assoc key (cdr map) :test #'equal)))
(defun cbor-hex (v)
  (with-output-to-string (s) (dotimes (i (length v)) (format s "~(~2,'0x~)" (aref v i)))))
(defun cbor-from-hex (h)
  (let ((v (%cbor-u8vec (floor (length h) 2))))
    (dotimes (i (length v) v) (setf (aref v i) (parse-integer h :start (* 2 i) :end (+ 2 (* 2 i)) :radix 16)))))
