;;;; fasl.lisp — the FASL cache: a loaded file's compiled MVM modules, kept so the
;;;; next load of the same file skips the compiler.
;;;;
;;;; WHAT IS CACHED.  Modus compiles each toplevel form of a loaded file to one
;;;; MVM bytecode module and runs it (mvm-eval-forms).  Bytecode is the portable
;;;; layer -- the same bytes run on the interpreter of every target, and the JIT
;;;; translates them per architecture -- so the cache keeps BYTECODE, never native
;;;; code, and a cache written by one image can serve another (host, QEMU, board)
;;;; whose compiler is the same.  Per toplevel form the cache holds either:
;;;;
;;;;   a MODULE: the bytecode, its function / runtime-call / lambda tables, the
;;;;     DEFUN names it publishes, and the literal constants it loads -- each
;;;;     described portably (a symbol by package and name, a global variable's
;;;;     cell by its key, data recursively); or
;;;;   SOURCE: just the form's span of the file, read and evaluated as usual.
;;;;
;;;; A form is cached as a module only when its COMPILE had no lasting effect of
;;;; its own: anything the compiler registers while compiling (a macro, a special,
;;;; a setf function, an inline definition, a struct accessor, a deftype, a
;;;; declaim) calls %FASL-TAINT, and a tainted form is kept as source.  That is
;;;; compile-file's rule too -- a fasl replays what a form DOES, not what
;;;; compiling it did -- and side effects of user macroexpanders are not replayed,
;;;; exactly as on SBCL.  Definition heads are kept as source outright as a second
;;;; guard (*FASL-SOURCE-HEADS*).
;;;;
;;;; THE KEY.  A file's cache entry is found by a hash of: the compiler
;;;; fingerprint (%FASL-COMPILER-FINGERPRINT, baked at build), *FEATURES* (the
;;;; reader saw them), the package the load started in, the file's text, and the
;;;; LOAD CHAIN -- every file loaded before it in this session.  Change any file
;;;; and everything loaded after it misses; nothing stale can be replayed.
;;;; (Not chained: forms evaluated outside a file, e.g. --eval.  Documented risk.)
;;;;
;;;; WHERE.  Hosted: $MODUS_FASL_DIR, else ~/.cache/modus/fasl/, one KEY.mfasl per
;;;; file.  Bare metal has no writable filesystem: *FASL-MEM* is an in-memory
;;;; table a loader (kiln) fills with fasls built on the host.  MODUS_FASL=0 turns
;;;; the cache off; MODUS_FASL=verify recompiles every file and compares.

(defvar *fasl-depth* nil "mvm-eval-forms nesting depth (see %MVM-EVAL-FORMS-1).")
(defvar *fasl-base* nil "*FASL-DEPTH* at the load loop's current EVAL.")
(defvar *fasl-outer* nil "Outermost mvm-eval-forms calls made by the current form.")
(defvar *fasl-slot* nil "The current form's record slot, taken by its first compile.")
(defvar *fasl-chain* nil "Hash of every file loaded so far this session.")
(defvar *fasl-mem* nil "Bare metal / pushed fasls: alist KEY -> bytes.")
(defvar *fasl-stats* nil "(hits misses modules sources rejected) this session.")
(defvar *fasl-bad* nil)
(defvar *fasl-times* nil "alist phase -> internal time spent")
(defun %fasl-time (phase t0)
  (let ((d (- (get-internal-real-time) t0)) (hit (assoc phase *fasl-times*)))
    (if hit (setf (cdr hit) (+ (cdr hit) d)) (setq *fasl-times* (cons (cons phase d) *fasl-times*)))))
(defvar *fasl-reasons* nil "Why forms were kept as source: alist reason -> count.")

;; *FASL-TAINT* / %FASL-TAINT live in compiler.lisp: the compiler calls it, on
;; the build host too.

;; %FASL-COMPILER-FINGERPRINT is generated by the build (build-cli-common.lisp,
;; *FASL-FINGERPRINT-SOURCE*): a hash of the compiler and macro sources.

(defun %fasl-stat (i)
  (unless *fasl-stats* (setq *fasl-stats* (list 0 0 0 0 0)))
  (let ((c (nthcdr i *fasl-stats*))) (setf (car c) (+ (car c) 1))))

;;; ------------------------------------------------------------------
;;; Hashing: two independent 32-bit FNV-1a lanes, fixnum arithmetic only.
;;; ------------------------------------------------------------------

(defun %fasl-hash-string (s)
  (let ((a 2166136261) (b 3735928559) (n (length s)) (i 0))
    (loop
      (when (>= i n) (return nil))
      (let ((c (char-code (char s i))))
        (setq a (logand (* (logxor a c) 16777619) 4294967295))
        (setq b (logand (* (logxor b (logand (+ c 41) 65535)) 16777619) 4294967295)))
      (setq i (+ i 1)))
    (format nil "~8,'0x~8,'0x~x" a b n)))

;;; ------------------------------------------------------------------
;;; A growable byte buffer: (vector . fill).
;;; ------------------------------------------------------------------

(defun %fb-new () (cons (make-array 4096 :element-type '(unsigned-byte 8)) 0))

(defun %fb-byte (fb b)
  (let ((v (car fb)) (n (cdr fb)))
    (when (>= n (length v))
      (let ((g (make-array (* 2 (length v)) :element-type '(unsigned-byte 8))))
        (replace g v)
        (setf (car fb) g)
        (setq v g)))
    (setf (aref v n) b)
    (setf (cdr fb) (+ n 1))))

(defun %fb-bulk (fb v)
  "Append byte vector V with one REPLACE (a per-byte loop made a file record
   cost seconds)."
  (let ((need (+ (cdr fb) (length v))))
    (when (> need (length (car fb)))
      (let ((g (make-array (max need (* 2 (length (car fb)))) :element-type '(unsigned-byte 8))))
        (replace g (car fb) :end2 (cdr fb))
        (setf (car fb) g)))
    (replace (car fb) v :start1 (cdr fb))
    (setf (cdr fb) need)))

(defun %fb-bytes (fb)
  (let ((r (make-array (cdr fb) :element-type '(unsigned-byte 8))))
    (replace r (car fb) :end2 (cdr fb))
    r))

(defun %fb-uint (fb n)
  "Unsigned LEB128."
  (loop
    (let ((low (logand n 127)))
      (setq n (ash n -7))
      (if (zerop n)
          (progn (%fb-byte fb low) (return nil))
          (%fb-byte fb (logior low 128))))))

(defun %fb-sint (fb n)
  (%fb-uint fb (if (< n 0) (- (* -2 n) 1) (* 2 n))))

(defun %fb-string (fb s)
  (let ((n (length s)))
    (%fb-uint fb n)
    (dotimes (i n) (%fb-uint fb (char-code (char s i))))))

;;; ------------------------------------------------------------------
;;; Value encoding.  Anything not listed REJECTS the form (it stays source).
;;; ------------------------------------------------------------------

(defun %fasl-reject (why)
  (throw '%fasl-reject why))

(defun %fasl-cell-key (v)
  "V's key when V is the live (key . value) cell of a global variable."
  ;; IGNORE-ERRORS: %GV-CELL signals TYPE-ERROR for an integer that is no name
  ;; key at all -- an ordinary (offset . name) pair reaches here
  (and (consp v) (integerp (car v))
       (fboundp (quote %gv-cell))
       (ignore-errors (eq v (funcall (quote %gv-cell) (car v))))
       (car v)))

(defun %fasl-enc (fb v unint depth)
  "Encode V.  UNINT is a (list) whose CAR is the uninterned symbols seen so far
   in this record, so one gensym stays one object."
  (when (> depth 2000) (%fasl-reject "too deep"))
  (handler-case (%fasl-enc-1 fb v unint depth)
    (error (e) (setq *fasl-bad* v) (%fasl-reject (format nil "enc ~a at depth ~d: ~a" (ignore-errors (type-of v)) depth
                                     (ignore-errors (princ-to-string e)))))))

(defun %fasl-enc-1 (fb v unint depth)
  (cond
    ((null v) (%fb-byte fb 0))
    ((eq v t) (%fb-byte fb 1))
    ;; CONSP FIRST: an image that still honours cons array wrappers calls a
    ;; (fixnum . string) pair a STRING -- and runtime-call tables are made of them
    ((consp v)
     (let ((key (%fasl-cell-key v)))
       (if key
           (progn (%fb-byte fb 10) (%fb-sint fb key))
           ;; a list: its proper elements, then its tail
           (let ((n 0) (c v))
             (loop (if (and (consp c) (< n 1000000)) (progn (setq n (+ n 1)) (setq c (cdr c))) (return nil)))
             (when (consp c) (%fasl-reject "circular list"))
             (%fb-byte fb 7) (%fb-uint fb n)
             (let ((c v))
               (dotimes (i n) (%fasl-enc fb (car c) unint (+ depth 1)) (setq c (cdr c)))
               (%fasl-enc fb c unint (+ depth 1)))))))
    ((integerp v) (%fb-byte fb 2) (%fb-sint fb v))
    ((characterp v) (%fb-byte fb 3) (%fb-uint fb (char-code v)))
    ;; any string, by its contents: a literal's identity and fill pointer do not
    ;; matter to code that loads it (and reader-made strings are not SIMPLE here)
    ((stringp v) (%fb-byte fb 4) (%fb-string fb v))
    ;; before CONSP / the vector arms: a pathname is cons-shaped here, and a
    ;; struct or CLOS instance is a #x32 array that would decode as a vector
    ((pathnamep v) (%fb-byte fb 14) (%fb-string fb (namestring v)))
    ((and (fboundp (quote %struct-instance-p)) (funcall (quote %struct-instance-p) v))
     (%fasl-reject "struct constant"))
    ((symbolp v)
     (let ((p (symbol-package v)))
       (if p
           (progn (%fb-byte fb 5) (%fb-string fb (package-name p))
                  (%fb-string fb (symbol-name v)))
           (let ((pos (position v (car unint))))
             (if pos
                 (progn (%fb-byte fb 15) (%fb-uint fb pos))
                 (progn (setf (car unint) (append (car unint) (list v)))
                        (%fb-byte fb 6) (%fb-string fb (symbol-name v))))))))
    ;; ELEMENT TYPE, not TYPEP: in modus (typep v '(simple-array (unsigned-byte 8)
    ;; (*))) answers T for a general vector too.
    ((and (vectorp v) (equal (array-element-type v) '(unsigned-byte 8)))
     (%fb-byte fb 9) (%fb-uint fb (length v))
     (%fb-bulk fb v))
    ((and (simple-vector-p v) (eq (array-element-type v) t))
     (%fb-byte fb 8) (%fb-uint fb (length v))
     (dotimes (i (length v)) (%fasl-enc fb (svref v i) unint (+ depth 1))))
    ((typep v 'ratio)
     (%fb-byte fb 11) (%fb-sint fb (numerator v)) (%fb-sint fb (denominator v)))
    ((typep v 'double-float)
     (multiple-value-bind (m e s) (integer-decode-float v)
       (%fb-byte fb 12) (%fb-sint fb m) (%fb-sint fb e) (%fb-sint fb s)))
    ((typep v 'single-float)
     (multiple-value-bind (m e s) (integer-decode-float v)
       (%fb-byte fb 13) (%fb-sint fb m) (%fb-sint fb e) (%fb-sint fb s)))
    (t (%fasl-reject "unencodable constant"))))

;;; Decoding: a cursor (vector . position).

(defun %fd-byte (cur)
  (let ((v (car cur)) (p (cdr cur)))
    (when (>= p (length v)) (%fasl-reject "truncated"))
    (setf (cdr cur) (+ p 1))
    (aref v p)))

(defun %fd-uint (cur)
  (let ((n 0) (shift 0))
    (loop
      (let ((b (%fd-byte cur)))
        (setq n (logior n (ash (logand b 127) shift)))
        (setq shift (+ shift 7))
        (when (< b 128) (return n))))))

(defun %fd-sint (cur)
  (let ((z (%fd-uint cur)))
    (if (oddp z) (- (ash (+ z 1) -1)) (ash z -1))))

(defun %fd-string (cur)
  (let* ((n (%fd-uint cur)) (s (make-string n)))
    (dotimes (i n) (setf (char s i) (code-char (%fd-uint cur))))
    s))

(defun %fasl-dec (cur unint)
  (let ((tag (%fd-byte cur)))
    (case tag
      (0 nil)
      (1 t)
      (2 (%fd-sint cur))
      (3 (code-char (%fd-uint cur)))
      (4 (%fd-string cur))
      (5 (let* ((pn (%fd-string cur)) (nm (%fd-string cur)) (p (find-package pn)))
           (unless p (%fasl-reject "no package"))
           (intern nm p)))
      (6 (let ((s (make-symbol (%fd-string cur))))
           (setf (car unint) (append (car unint) (list s)))
           s))
      (15 (nth (%fd-uint cur) (car unint)))
      (7 (let* ((n (%fd-uint cur)) (head nil) (tail nil))
           (dotimes (i n)
             (let ((cell (list (%fasl-dec cur unint))))
               (if tail (setf (cdr tail) cell) (setq head cell))
               (setq tail cell)))
           (let ((end (%fasl-dec cur unint)))
             (if tail (progn (setf (cdr tail) end) head) end))))
      (8 (let* ((n (%fd-uint cur)) (v (make-array n)))
           (dotimes (i n) (setf (svref v i) (%fasl-dec cur unint)))
           v))
      (9 (let* ((n (%fd-uint cur)) (v (make-array n :element-type '(unsigned-byte 8)))
                (p (cdr cur)))
           (when (> (+ p n) (length (car cur))) (%fasl-reject "truncated"))
           (replace v (car cur) :start2 p :end2 (+ p n))
           (setf (cdr cur) (+ p n))
           v))
      (10 (let* ((key (%fd-sint cur))
                 (c (and (fboundp (quote %gv-cell)) (funcall (quote %gv-cell) key))))
            (unless (consp c) (%fasl-reject "no global cell"))
            c))
      (11 (let ((n (%fd-sint cur))) (/ n (%fd-sint cur))))
      (12 (let* ((m (%fd-sint cur)) (e (%fd-sint cur)) (s (%fd-sint cur)))
            (* s (scale-float (float m 1d0) e))))
      ;; a single-float decodes to a double-width mantissa here: rebuild exactly
      ;; as a double, then narrow
      (13 (let* ((m (%fd-sint cur)) (e (%fd-sint cur)) (s (%fd-sint cur)))
            (coerce (* s (scale-float (float m 1d0) e)) 'single-float)))
      (14 (pathname (%fd-string cur)))
      (otherwise (%fasl-reject "bad tag")))))

(defun %fasl-encode (v)
  (let ((fb (%fb-new))) (%fasl-enc fb v (list nil) 0) (%fb-bytes fb)))

(defun %fasl-decode (bytes)
  (%fasl-dec (cons bytes 0) (list nil)))

;;; ------------------------------------------------------------------
;;; Recording one form's module (called by %MVM-EVAL-FORMS-2 after the build,
;;; before the run).
;;; ------------------------------------------------------------------

(defun %fasl-source-heads ()
  "Toplevel heads always kept as source -- the second guard, for compile-time
   behaviour no registry write announces: DEFPACKAGE's package work,
   DEFCONSTANT's compile-time EVAL, EVAL-WHEN, DEFSTRUCT's accessor tables,
   the setf-expander definers, and the macro definers (also tainted).  DEFVAR,
   DECLAIM, IN-PACKAGE and the CLOS definers are not here: what their compile
   registers is data (%FASL-EFFECT) or nothing, and the taint catches the rest."
  '("DEFMACRO" "DEFINE-COMPILER-MACRO" "DEFINE-SYMBOL-MACRO" "DEFSTRUCT"
    "DEFSETF" "DEFINE-SETF-EXPANDER" "DEFINE-MODIFY-MACRO" "DEFCONSTANT"
    "DEFPACKAGE" "EVAL-WHEN" "DEFINE-PACKAGE" "DEFSYSTEM"))

(defun %fasl-source-head-p (forms)
  (let ((f (car forms)))
    (and (consp f) (symbolp (car f))
         (member (symbol-name (car f)) (%fasl-source-heads) :test (function string=)))))

(defun %fasl-walk-bc (bc fn)
  "Call FN with (opcode operands end-position) for each instruction of BC."
  (let ((pos 0) (n (length bc)))
    (loop
      (when (>= pos n) (return nil))
      (multiple-value-bind (op operands np) (decode-instruction-mv bc pos)
        (unless (and (integerp np) (> np pos)) (%fasl-reject "undecodable bytecode"))
        (funcall fn op operands np)
        (setq pos np)))))

(defun %fasl-put-u64 (bc end v)
  "Store V little-endian in the 8 bytes ending at END."
  (dotimes (k 8)
    (setf (aref bc (+ (- end 8) k)) (logand (ash v (* -8 k)) 255))))

(defun %fasl-record (slot forms bc entry ft-list fn-table rt-table lam-offsets
                     persist-names lam-bearing taint0)
  "Encode this module into SLOT's CAR, or leave it NIL (the form stays source)."
  (let ((t0 (get-internal-real-time)))
    (prog1 (%fasl-record-1 slot forms bc entry ft-list fn-table rt-table lam-offsets
                           persist-names lam-bearing taint0)
      (%fasl-time :record t0))))

(defun %fasl-record-1 (slot forms bc entry ft-list fn-table rt-table lam-offsets
                       persist-names lam-bearing taint0)
  (let ((r (catch '%fasl-reject
             (handler-case
                 (progn
                   (unless (eql taint0 *fasl-taint*)
                     (%fasl-reject (format nil "compile registered something (~a)" *fasl-taint-who*)))
                   (when (%fasl-source-head-p forms)
                     (%fasl-reject (format nil "definition head ~a" (car (car forms)))))
                   ;; constants: renumber every pool index this bytecode loads,
                   ;; densely, in first-use order
                   (let ((bc2 (copy-seq bc)) (idxs nil) (k 0))
                     (%fasl-walk-bc bc2
                       (lambda (op operands np)
                         (cond
                           ((or (eql op +op-li-addr+) (eql op +op-li-taddr+))
                            (%fasl-reject "layout address"))
                           ((eql op +op-li-const+)
                            (let* ((idx (cadr operands)) (hit (assoc idx idxs)))
                              (unless hit
                                (setq hit (cons idx k))
                                (setq idxs (cons hit idxs))
                                (setq k (+ k 1)))
                              (%fasl-put-u64 bc2 np (cdr hit)))))))
                     (let ((consts (mapcar (lambda (p) (gethash (car p) *e2-const-pool*))
                                           (reverse idxs)))
                           (rt nil) (lam nil))
                       ;; the runtime-call names (positive keys; the negative ones
                       ;; are per-process call caches, rebuilt on replay)
                       (maphash (lambda (key v) (when (and (integerp key) (> key 0)) (push (cons key v) rt)))
                                rt-table)
                       (maphash (lambda (key v) (push (cons key v) lam)) lam-offsets)
                       (let ((rec (list 1 bc2 entry ft-list fn-table rt lam persist-names
                                       (and (or lam-bearing (%mvm-forms-define-methods-p forms)) t)
                                       consts
                                       (and (consp *fasl-effects*) (reverse (car *fasl-effects*))))))
                         (%fasl-encode rec)))))
               (error (e) (%fasl-reject (format nil "error while recording: ~a"
                                                (ignore-errors (princ-to-string e)))))))))
    (if (stringp r)
        (progn (%fasl-stat 4)
               (let ((hit (assoc r *fasl-reasons* :test (function string=))))
                 (if hit (setf (cdr hit) (+ (cdr hit) 1))
                     (setq *fasl-reasons* (cons (cons r 1) *fasl-reasons*)))))
        (setf (car slot) r))))

;;; ------------------------------------------------------------------
;;; Replaying one module.
;;; ------------------------------------------------------------------

(defun %fasl-prepare (bytes)
  "Decode a recorded module and make it runnable here: constants re-registered
   in this process's quote pool, the bytecode's pool indices moved to them.
   Throws %FASL-REJECT (caught by the caller, which then compiles the source)."
  (let* ((rec (%fasl-decode bytes)))
    (unless (and (consp rec) (eql (car rec) 1)) (%fasl-reject "bad record"))
    (let* ((bc (copy-seq (nth 1 rec))) (entry (nth 2 rec)) (ft-list (nth 3 rec))
           (fn-table (nth 4 rec)) (rt (nth 5 rec)) (lam (nth 6 rec))
           (persist (nth 7 rec)) (lam-bearing (nth 8 rec)) (consts (nth 9 rec))
           (idx (mapcar (function %e2-const-register) consts))
           (rt-table (make-hash-table)) (lam-offsets (make-hash-table)))
      (%fasl-walk-bc bc
        (lambda (op operands np)
          (when (eql op +op-li-const+)
            (%fasl-put-u64 bc np (nth (cadr operands) idx)))))
      (dolist (p rt)
        (setf (gethash (car p) rt-table) (cdr p))
        (setf (gethash (- (car p)) rt-table) (cons nil 0)))
      (dolist (p lam) (setf (gethash (car p) lam-offsets) (cdr p)))
      (list bc entry ft-list fn-table rt-table lam-offsets persist lam-bearing (nth 10 rec)))))

(defun %fasl-apply-effect (e)
  "Redo one logged compile-time registration (see %FASL-EFFECT)."
  (let ((k (car e)) (a (cdr e)))
    (cond ((eq k :special) (%note-runtime-special (car a)))
          ((eq k :optimize) (%declaim-note-optimize (car a)))
          ((eq k :declaim-special) (%declaim-note-special (car a)))
          ((eq k :declaim-inline) (%declaim-note-inline (car a)))
          ((eq k :declaim-type) (%declaim-note-type (car a)))
          ((eq k :inline-defun) (%inline-record-defun (car a) (cadr a) (caddr a)))
          ((eq k :setf-function) (%register-setf-function (car a))))))

(defun %fasl-run-prepared (p)
  "Called from %MVM-EVAL-FORMS-2 (the marker form): redo the module's logged
   compile-time registrations, then publish and run it."
  (dolist (e (nth 8 p)) (%fasl-apply-effect e))
  (%mvm-eval-publish-and-run nil (nth 0 p) (nth 1 p) (nth 2 p) (nth 3 p) (nth 4 p)
                             (nth 5 p) (nth 6 p) (nth 7 p) nil))

;;; ------------------------------------------------------------------
;;; Storage.
;;; ------------------------------------------------------------------

(defun %fasl-mode ()
  "NIL (off), :ON or :VERIFY."
  (let ((v (ignore-errors (%cli-getenv "MODUS_FASL"))))
    (cond ((and v (string= v "0")) nil)
          ((and v (string-equal v "verify")) :verify)
          (t :on))))

(defun %fasl-dir ()
  (let ((d (ignore-errors (%cli-getenv "MODUS_FASL_DIR"))))
    (if (and d (> (length d) 0))
        (if (char= (char d (- (length d) 1)) #\/) d (concatenate 'string d "/"))
        (let ((h (ignore-errors (%cli-getenv "HOME"))))
          (and h (> (length h) 0) (concatenate 'string h "/.cache/modus/fasl/"))))))

(defun fasl-mem-put (key bytes)
  "Make BYTES the fasl for KEY in this image (bare metal: kiln pushes them)."
  (setq *fasl-mem* (cons (cons key bytes) (remove key *fasl-mem* :key (function car) :test (function string=))))
  key)

(defun %fasl-get (key)
  (or (cdr (assoc key *fasl-mem* :test (function string=)))
      (let ((d (%fasl-dir)))
        (and d
             (ignore-errors
              (with-open-file (i (concatenate 'string d key ".mfasl")
                                 :element-type '(unsigned-byte 8) :if-does-not-exist nil)
                (and i
                     (let ((b (make-array (file-length i) :element-type '(unsigned-byte 8))))
                       (read-sequence b i)
                       b))))))))

(defun %fasl-put (key bytes)
  (let ((d (%fasl-dir)))
    (when d
      (ignore-errors
       (let ((path (concatenate 'string d key ".mfasl")))
         (ensure-directories-exist path)
         (with-open-file (o path :direction :output :element-type '(unsigned-byte 8)
                                 :if-exists :supersede :if-does-not-exist :create)
           (write-sequence bytes o))
         t)))))

;;; ------------------------------------------------------------------
;;; The load loops: %FASL-OPEN / %FASL-READ / %FASL-EVAL / %FASL-CLOSE.
;;; An FX is a list: (mode key text pos entries cached ok)
;;;   mode :record | :replay   entries: recorded (start end payload), newest first
;;;   cached: the replay queue (or, verifying, the old record to compare)
;;; ------------------------------------------------------------------

(defun %fasl-features-string ()
  (let ((names (mapcar (lambda (f) (if (symbolp f) (symbol-name f) (princ-to-string f))) *features*)))
    (format nil "~{~a~^,~}" (sort names (function string<)))))

(defun %fasl-key (text)
  (%fasl-hash-string
   (format nil "~a|~a|~a|~a|~a"
           (%fasl-compiler-fingerprint)
           (%fasl-hash-string (%fasl-features-string))
           (if *package* (package-name *package*) "")
           (or *fasl-chain* "")
           (%fasl-hash-string text))))

(defun %fasl-active-p ()
  "The cache is in use for this load: switched on, main thread, runtime eval."
  (and (%fasl-mode) (%mvm-on-main-thread-p) (not *static-build-p*)))

(defun %fasl-stream-text (stream)
  "STREAM's whole remaining text when it is a FILE being LOADed and the cache is
   active -- else NIL, and STREAM is left untouched."
  (when (and (typep stream 'file-stream) (%fasl-active-p))
    (with-output-to-string (o)
      (loop
        (let ((c (read-char stream nil nil)))
          (if c (write-char c o) (return nil)))))))

(defun %fasl-open (text)
  "Begin loading TEXT.  NIL when the cache is off (then the caller loads as before)."
  (let ((t0 (get-internal-real-time)))
    (prog1 (%fasl-open-1 text) (%fasl-time :open t0))))

(defun %fasl-open-1 (text)
  (let ((mode (%fasl-mode)))
    (when (and (stringp text) (%fasl-active-p))
      (let* ((t0 (get-internal-real-time))
             (key (prog1 (%fasl-key text) (%fasl-time :open-key t0)))
             (t1 (get-internal-real-time))
             (bytes (prog1 (%fasl-get key) (%fasl-time :open-read t1)))
             (t2 (get-internal-real-time))
             (rec (prog1 (and bytes (catch '%fasl-reject
                                      (handler-case (%fasl-decode bytes) (error (e) nil))))
                    (%fasl-time :open-decode t2))))
        (if (and (consp rec) (eq (car rec) :modus-fasl) (equal (caddr rec) key))
            (if (eq mode :verify)
                (list :record key text 0 nil (cadddr rec) t)
                (progn (%fasl-stat 0) (list :replay key text 0 nil (cadddr rec) t)))
            ;; Nowhere to keep a record (bare metal, no $HOME): do not pay for
            ;; one -- the board spent 3 s of boot recording its shims
            (when (%fasl-dir)
              (%fasl-stat 1) (list :record key text 0 nil nil t)))))))

(defun %fasl-read (fx eof)
  "The next toplevel form, EOF at the end -- or, replaying, a module marker."
  (let ((text (nth 2 fx)))
    (if (eq (car fx) :replay)
        (let ((e (car (nth 5 fx))))
          (if (null e)
              eof
              (progn
                (setf (nth 5 fx) (cdr (nth 5 fx)))
                (if (nth 2 e)
                    (list '%fasl-module-marker (nth 2 e) (nth 0 e) (nth 1 e))
                    (progn (%fasl-stat 3)
                           (values (read-from-string text t nil :start (nth 0 e))))))))
        (let ((start (nth 3 fx)))
          (multiple-value-bind (form end) (read-from-string text nil eof :start start)
            (setf (nth 3 fx) end)
            (unless (eq form eof)
              (setf (nth 4 fx) (cons (list start end nil) (nth 4 fx))))
            form)))))

(defun %fasl-eval (fx form)
  "EVAL FORM as the load loop would, recording or replaying through FX."
  (cond
    ((and (consp form) (eq (car form) '%fasl-module-marker))
     (let ((p (let ((t0 (get-internal-real-time)))
                (prog1 (catch '%fasl-reject
                         (handler-case (%fasl-prepare (cadr form)) (error (e) "prepare error")))
                  (%fasl-time :prepare t0)))))
       (if (stringp p)
           ;; the module cannot be rebuilt here: compile its source instead
           (progn (%fasl-stat 4)
                  (eval (values (read-from-string (nth 2 fx) t nil :start (caddr form)))))
           (progn (%fasl-stat 2)
                  (let ((t0 (get-internal-real-time)))
                    (multiple-value-prog1 (eval (list '%fasl-module-marker p))
                      (%fasl-time :run-module t0)))))))
    ((eq (car fx) :record)
     (let ((entry (car (nth 4 fx)))
           (slot (list nil))
           (sv-base *fasl-base*) (sv-outer *fasl-outer*) (sv-slot *fasl-slot*))
       (setq *fasl-base* (or *fasl-depth* 0))
       (setq *fasl-outer* 0)
       (setq *fasl-slot* slot)
       (let ((val nil) (outer 0))
         (unwind-protect
              (setq val (multiple-value-list (eval form)))
           (setq outer *fasl-outer*)
           (setq *fasl-effects* nil)
           (setq *fasl-base* sv-base) (setq *fasl-outer* sv-outer) (setq *fasl-slot* sv-slot))
         ;; exactly one outermost compile, and it recorded: the module IS the form
         (when (and (eql outer 1) (car slot) (consp entry))
           (setf (nth 2 entry) (car slot)))
         (values-list val))))
    (t (eval form))))

(defun %fasl-close (fx ok)
  "End of the file.  OK: every form was read (no read error stopped the load)."
  (let ((t0 (get-internal-real-time)))
    (prog1 (%fasl-close-1 fx ok) (%fasl-time :close t0))))

(defun %fasl-close-1 (fx ok)
  (when fx
    (when (and ok (eq (car fx) :record))
      (let ((entries (reverse (nth 4 fx))))
        (when (nth 5 fx)                 ; verifying against an old record
          (let ((same 0) (diff 0))
            (do ((a entries (cdr a)) (b (nth 5 fx) (cdr b))) ((or (null a) (null b)))
              (if (equalp (nth 2 (car a)) (nth 2 (car b))) (setq same (+ same 1)) (setq diff (+ diff 1))))
            (format *error-output* "~&FASL-VERIFY ~a: ~d same, ~d differ, ~d vs ~d forms~%"
                    (nth 1 fx) same diff (length entries) (length (nth 5 fx)))))
        (dolist (e entries) (if (nth 2 e) (%fasl-stat 2) (%fasl-stat 3)))
        (let* ((t0 (get-internal-real-time))
               (b (prog1 (%fasl-encode (list :modus-fasl 1 (nth 1 fx) entries)) (%fasl-time :close-encode t0)))
               (t1 (get-internal-real-time)))
          (%fasl-put (nth 1 fx) b)
          (%fasl-time :close-write t1))))
    (setq *fasl-chain* (%fasl-hash-string (format nil "~a+~a" (or *fasl-chain* "") (nth 1 fx))))))

(defun fasl-stats ()
  "(:hits :misses :modules :sources :rejected) for this session."
  (let ((s (or *fasl-stats* (list 0 0 0 0 0))))
    (list :hits (nth 0 s) :misses (nth 1 s) :modules (nth 2 s) :sources (nth 3 s) :rejected (nth 4 s)
          :why *fasl-reasons* :ms (mapcar (lambda (p) (cons (car p) (round (* 1000 (cdr p)) internal-time-units-per-second))) *fasl-times*))))
