#!/bin/bash
# build-ansi-file-runner.sh — generate a runner that loads aux + ONE test
# file + runs.  Used by run-ansi-per-file.sh to run each test file in
# isolation (fresh /tmp/modus process), avoiding state-pollution cascades
# from running ~2000+ tests in a single process.
#
# Usage:
#   scripts/build-ansi-file-runner.sh <output.lisp> <test-file-abspath>

set -e

AUX=/home/claude/modus-ref/ansi-test/auxiliary/ansi_aux
LITE=/home/claude/modus/scripts/lite-universe.lisp
OUT=$1
TEST_FILE=$2

cat > "$OUT" <<LISP_EOF
;;; Auto-generated by build-ansi-file-runner.sh.  Runs $TEST_FILE in isolation.
(%install-runtime-cl-macros)
(load "$LITE")
(load "/home/claude/modus-ref/ansi-test/auxiliary/ansi-aux-macros.lsp")
LISP_EOF

# All aux files
for f in $AUX/ansi-aux.lsp $AUX/cons-aux.lsp $AUX/numbers-aux.lsp \
         $AUX/string-aux.lsp $AUX/char-aux.lsp $AUX/types-aux.lsp \
         $AUX/array-aux.lsp $AUX/subseq-aux.lsp $AUX/remove-aux.lsp \
         $AUX/remove-duplicates-aux.lsp $AUX/printer-aux.lsp \
         $AUX/sort-aux.lsp $AUX/search-aux.lsp; do
  if [ -f "$f" ]; then
    echo "(handler-case (load \"$f\") (t (c) nil))" >> "$OUT"
  fi
done

# Modus-friendly stubs after aux
echo "(load \"/home/claude/modus/scripts/aux-stubs.lisp\")" >> "$OUT"

# The single test file
echo "(handler-case (load \"$TEST_FILE\") (t (c) nil))" >> "$OUT"

echo "(rt-run-registered-tests)" >> "$OUT"
