#!/bin/bash
# build-ansi-runner.sh — generate a Modus script that loads ANSI test
# files from one or more tests/ subdirs and runs them.
#
# The Modus runtime image (/tmp/modus, from `sbcl --script
# mvm/build-generic.lisp`) reads its argv[1] as a Lisp source file and
# LOADs it.  This script emits such a file: aux loads + per-subdir
# test loads + (rt-run-registered-tests) at the end.
#
# Usage:
#   scripts/build-ansi-runner.sh <output.lisp> "<subdir1 subdir2 ...>"
#   /tmp/modus <output.lisp> | awk '/^P:/{p++} /^FAIL/{f++} /^CRASH/{c++} END {print "P="p" F="f" C="c}'

set -e

TESTS_ROOT=/home/claude/modus-ref/ansi-test/tests
AUX=/home/claude/modus-ref/ansi-test/auxiliary/ansi_aux
LITE="$(cd "$(dirname "$0")" && pwd)/lite-universe.lisp"
OUT=$1
SUBDIRS="$2"

cat > "$OUT" <<LISP_EOF
;;; Auto-generated by build-ansi-runner.sh.  Loads $SUBDIRS.
(%install-runtime-cl-macros)
(load "$LITE")
(load "/home/claude/modus-ref/ansi-test/auxiliary/ansi-aux-macros.lsp")
LISP_EOF

# Aux files (broad coverage)
for f in $AUX/ansi-aux.lsp $AUX/cons-aux.lsp $AUX/numbers-aux.lsp \
         $AUX/string-aux.lsp $AUX/char-aux.lsp $AUX/types-aux.lsp \
         $AUX/array-aux.lsp $AUX/subseq-aux.lsp $AUX/remove-aux.lsp \
         $AUX/remove-duplicates-aux.lsp $AUX/printer-aux.lsp \
         $AUX/sort-aux.lsp $AUX/search-aux.lsp; do
  if [ -f "$f" ]; then
    echo "(handler-case (load \"$f\") (t (c) nil))" >> "$OUT"
  fi
done

# Stubs AFTER aux so they win via last-defun-wins (in particular
# make-scaffold-copy / check-scaffold-copy — the official defstruct
# versions fail at runtime EVAL and silently kill rt-run).
echo "(load \"$(cd "$(dirname "$0")" && pwd)/aux-stubs.lisp\")" >> "$OUT"

# Test files from each subdir, alphabetical, skipping load.lsp + *-aux.lsp.
for subdir in $SUBDIRS; do
  if [ -d "$TESTS_ROOT/$subdir" ]; then
    for f in "$TESTS_ROOT/$subdir"/*.lsp; do
      bn=$(basename "$f")
      if [ "$bn" != "load.lsp" ] && [[ "$bn" != *-aux.lsp ]]; then
        echo "(handler-case (load \"$f\") (t (c) nil))" >> "$OUT"
      fi
    done
  fi
done

echo "(rt-run-registered-tests)" >> "$OUT"
echo "Wrote $(wc -l < "$OUT") lines to $OUT"
