(defun say (k v) (princ (concatenate (quote string) k "=" (princ-to-string v))) (terpri) (finish-output))
(say "S1" (if (find-package "ITERATE") 1 0))
(say "S2" (handler-case (install-tarball "/home/claude/lf/tars/iterate.tar" "iterate") (t (c) :abort)))
(say "S3" (package-name *package*))
(say "S4" (if (find-package "ITERATE") 1 0))
(say "S5" (handler-case (eval (read-from-string "(+ 1 2)")) (t (c) (list :ERR c))))
(say "S6" (handler-case (eval (read-from-string "(if (fboundp 'iterate::bang-var-num) 1 0)")) (t (c) (list :ERR c))))
(say "S7" (handler-case (eval (read-from-string "(iterate::make-bang-var 1)")) (t (c) (list :ERR c))))
(say "END" "ok")
