(defun say (k v) (princ (concatenate (quote string) k "=" (princ-to-string v))) (terpri) (finish-output))
(defun pr2 (name src) (say name (handler-case (eval (read-from-string src)) (t (c) (list :ERR c)))))
(say "S2" (handler-case (install-tarball "/home/claude/lf/tars/iterate.tar" "iterate") (t (c) :abort)))
(pr2 "a.mbv"  "(iterate::make-bang-var 1)")
(pr2 "b.bvp"  "(iterate::bang-var? (iterate::make-bang-var 1))")
(pr2 "c.bvn"  "(iterate::bang-var-num (iterate::make-bang-var 1))")
(pr2 "d.bvs"  "(iterate::bang-vars (list 'iterate::foo (iterate::make-bang-var 1)))")
(pr2 "e.sort" "(sort (list (iterate::make-bang-var 2) (iterate::make-bang-var 1)) (function <) :key (function iterate::bang-var-num))")
(pr2 "f.lof"  "(if (fboundp 'iterate::list-of-forms?) 1 0)")
(pr2 "g.nobang" "(funcall (function iterate::sharpL-reader) (make-string-input-stream \"(list 1)\") #\\L nil)")
(pr2 "h.bang"   "(funcall (function iterate::sharpL-reader) (make-string-input-stream \"(list iterate::!1)\") #\\L nil)")
(say "END" "ok")
