(defun say (k v) (princ (concatenate (quote string) k "=" (princ-to-string v))) (terpri) (finish-output))
(say "S2" (handler-case (install-tarball "/home/claude/lf/tars/iterate.tar" "iterate") (t (c) :abort)))
(say "a.mbv"  (handler-case (eval (read-from-string "(iterate::make-bang-var 1)")) (t (c) (list :ERR c))))
(say "b.bvp"  (handler-case (eval (read-from-string "(iterate::bang-var? (iterate::make-bang-var 1))")) (t (c) (list :ERR c))))
(say "c.bvn"  (handler-case (eval (read-from-string "(iterate::bang-var-num (iterate::make-bang-var 1))")) (t (c) (list :ERR c))))
(say "d.bvs"  (handler-case (eval (read-from-string "(iterate::bang-vars (list 'iterate::foo (iterate::make-bang-var 1)))")) (t (c) (list :ERR c))))
(say "e.sort" (handler-case (eval (read-from-string "(sort (list (iterate::make-bang-var 2) (iterate::make-bang-var 1)) (function <) :key (function iterate::bang-var-num))")) (t (c) (list :ERR c))))
(say "f.lof"  (handler-case (eval (read-from-string "(if (fboundp 'iterate::list-of-forms?) 1 0)")) (t (c) (list :ERR c))))
(say "g.nobang" (handler-case (eval (read-from-string "(funcall (function iterate::sharpL-reader) (make-string-input-stream \"(list 1)\") #\\L nil)")) (t (c) (list :ERR c))))
(say "h.bang"   (handler-case (eval (read-from-string "(funcall (function iterate::sharpL-reader) (make-string-input-stream \"(list iterate::!1)\") #\\L nil)")) (t (c) (list :ERR c))))
(say "END" "ok")
