(defun say (k v) (princ (concatenate (quote string) k "=" (princ-to-string v))) (terpri) (finish-output))
(say "S2" (handler-case (install-tarball "/home/claude/lf/tars/iterate.tar" "iterate") (t (c) :abort)))
(say "p1.loop-collect" (handler-case (eval (read-from-string "(loop for i from 1 to 1 collect (iterate::make-bang-var i))")) (t (c) (list :ERR c))))
(say "p2.mapcar-ignore" (handler-case (eval (read-from-string "(mapcar (lambda (x) (declare (ignore x)) (gensym)) (list 'a))")) (t (c) (list :ERR c))))
(say "p3.mapcan2" (handler-case (eval (read-from-string "(mapcan (lambda (a b) (if a (list b) nil)) (list 1) (list 2))")) (t (c) (list :ERR c))))
(say "p4.mapcan2-member" (handler-case (eval (read-from-string "(mapcan (lambda (v tv) (when (member v (list 1)) (list (list v tv)))) (list 1) (list 'g))")) (t (c) (list :ERR c))))
(say "p5.gensym" (handler-case (eval (read-from-string "(gensym)")) (t (c) (list :ERR c))))
(say "p6.symbol-macrolet" (handler-case (eval (read-from-string "(let ((g 5)) (symbol-macrolet ((x g)) x))")) (t (c) (list :ERR c))))
(say "END" "ok")
