(defun say (k v) (princ (concatenate (quote string) k "=" (princ-to-string v))) (terpri) (finish-output))
(defun zsay (k v) (princ (concatenate (quote string) "  [" k "]=" (princ-to-string v))) (terpri) (finish-output))
(say "S2" (handler-case (install-tarball "/home/claude/lf/tars/iterate.tar" "iterate") (t (c) :abort)))
(say "DEF" (handler-case (eval (read-from-string
"(defun iterate::zsharp (stream subchar n-args)
  (declare (ignore subchar))
  (let* ((form (read stream t nil t))
         (m1 (zsay \"M1-form\" form))
         (refd-!vars (sort (iterate::bang-vars (macroexpand form)) (function <) :key (function iterate::bang-var-num)))
         (m2 (zsay \"M2-refd\" refd-!vars))
         (bang-var-nums (mapcar (function iterate::bang-var-num) refd-!vars))
         (m3 (zsay \"M3-nums\" bang-var-nums))
         (max-bv-num (if refd-!vars (car (last bang-var-nums)) 0))
         (m4 (zsay \"M4-max\" max-bv-num)))
    (cond ((null n-args) (setq n-args max-bv-num))
          ((< n-args max-bv-num) (error \"too few\")))
    (zsay \"M5-nargs\" n-args)
    (let* ((all-!vars (loop for i from 1 to n-args collect (iterate::make-bang-var i)))
           (m6 (zsay \"M6-all\" all-!vars))
           (formals (mapcar (lambda (x) (declare (ignore x)) (gensym)) all-!vars))
           (m7 (zsay \"M7-formals\" formals)))
      (zsay \"M8-ignore\" (mapcan (lambda (!var tempvar)
                                    (unless (member !var refd-!vars) (list tempvar)))
                                  all-!vars formals))
      (zsay \"M9-smlet\" (mapcan (lambda (!var tempvar)
                                   (when (member !var refd-!vars) (list (list !var tempvar))))
                                 all-!vars formals))
      (zsay \"M10-lof\" (iterate::list-of-forms? form))
      (let ((r `#'(lambda ,formals
                    (symbol-macrolet ,(mapcan (lambda (!var tempvar)
                                                (when (member !var refd-!vars) (list (list !var tempvar))))
                                              all-!vars formals)
                      ,@(if (iterate::list-of-forms? form) form (list form))))))
        (zsay \"M11-result\" r)
        r))))")) (t (c) (list :ERR c))))
(say "Z.nobang" (handler-case (eval (read-from-string "(funcall (function iterate::zsharp) (make-string-input-stream \"(list 1)\") #\\L nil)")) (t (c) (list :ERR c))))
(say "Z.bang" (handler-case (eval (read-from-string "(funcall (function iterate::zsharp) (make-string-input-stream \"(list iterate::!1)\") #\\L nil)")) (t (c) (list :ERR c))))
(say "END" "ok")
