(defun say (k v) (princ (concatenate (quote string) k "=" (princ-to-string v))) (terpri) (finish-output))
(say "S2" (handler-case (install-tarball "/home/claude/lf/tars/iterate.tar" "iterate") (t (c) :abort)))
(say "DEF" (handler-case (eval (read-from-string
"(eval-when (:compile-toplevel :execute)
  (defun iterate::zew (stream subchar n-args)
  (declare (ignore subchar))
  (let* ((form (read stream t nil t))
         (refd-!vars (sort (iterate::bang-vars (macroexpand form))
                           (function <) :key (function iterate::bang-var-num)))
         (bang-var-nums (mapcar (function iterate::bang-var-num) refd-!vars))
         (max-bv-num (if refd-!vars (car (last bang-var-nums)) 0)))
    (cond ((null n-args) (setq n-args max-bv-num))
          ((< n-args max-bv-num) (error \"too few\")))
    (let* ((all-!vars (loop for i from 1 to n-args collect (iterate::make-bang-var i)))
           (formals (mapcar (lambda (x) (declare (ignore x)) (gensym)) all-!vars)))
      `#'(lambda ,formals
           ,@(let ((ignore (mapcan (lambda (!var tempvar)
                                     (unless (member !var refd-!vars) (list tempvar)))
                                   all-!vars formals)))
               (if ignore `((declare (ignore ,@ignore)))))
           (symbol-macrolet ,(mapcan (lambda (!var tempvar)
                                       (when (member !var refd-!vars) (list (list !var tempvar))))
                                     all-!vars formals)
             ,@(if (iterate::list-of-forms? form) form (list form))))))))")) (t (c) (list :ERR c))))
(say "FB" (handler-case (eval (read-from-string "(if (fboundp 'iterate::zew) 1 0)")) (t (c) (list :ERR c))))
(say "W.nobang" (handler-case (eval (read-from-string "(funcall (function iterate::zew) (make-string-input-stream \"(list 1)\") #\\L nil)")) (t (c) (list :ERR c))))
(say "W.bang" (handler-case (eval (read-from-string "(funcall (function iterate::zew) (make-string-input-stream \"(list iterate::!1)\") #\\L nil)")) (t (c) (list :ERR c))))
(say "END" "ok")
