(defun say (k v) (princ (concatenate (quote string) k "=" (princ-to-string v))) (terpri) (finish-output))
(defun probe (name src)
  (say name (handler-case (eval (read-from-string src))
              (t (c) (list :ERR c)))))
(handler-case (install-tarball "/home/claude/lf/tars/iterate.tar" "iterate") (t (c) :abort))
(say "MARK" "installed")
(probe "q.pkg" "(if (find-package \"ITERATE\") 1 0)")
(probe "q.sharpL" "(if (fboundp 'iterate::sharpL-reader) 1 0)")
(probe "q.bangvars" "(if (fboundp 'iterate::bang-vars) 1 0)")
(probe "q.bangvarnum" "(if (fboundp 'iterate::bang-var-num) 1 0)")
(probe "q.makebangvar" "(if (fboundp 'iterate::make-bang-var) 1 0)")
(probe "q.bangvarp" "(if (fboundp 'iterate::bang-var?) 1 0)")
(probe "q.listofforms" "(if (fboundp 'iterate::list-of-forms?) 1 0)")
(probe "r.mbv" "(iterate::make-bang-var 1)")
(probe "r.bvp" "(iterate::bang-var? (iterate::make-bang-var 1))")
(probe "r.bvn" "(iterate::bang-var-num (iterate::make-bang-var 1))")
(probe "r.bvs" "(iterate::bang-vars (list 'iterate::a (iterate::make-bang-var 1)))")
(probe "r.sort" "(sort (list (iterate::make-bang-var 2) (iterate::make-bang-var 1)) #'< :key #'iterate::bang-var-num)")
(probe "r.nobang" "(funcall #'iterate::sharpL-reader (make-string-input-stream \"(list 1)\") #\\L nil)")
(probe "r.bang" "(funcall #'iterate::sharpL-reader (make-string-input-stream \"(list iterate::!1)\") #\\L nil)")
(say "END" "ok")
