(defun say (k v) (princ (concatenate (quote string) k "=" (princ-to-string v))) (terpri) (finish-output))
(defun ldf (path pkgname)
  (let ((p *package*) (r nil))
    (setq *package* (find-package pkgname))
    (setq r (handler-case (%it-eval-source (tar-bytes-to-string (%it-slurp-bytes path)) path)
              (t (c) (list :ERR c))))
    (setq *package* p) r))
(say "L1" (ldf "/home/claude/ws-iter/esc2/itpkg.lisp" "COMMON-LISP-USER"))
(say "L2" (ldf "/home/claude/ws-iter/esc2/slice.lisp" "ITERATE"))
(say "FB" (handler-case (eval (read-from-string "(if (fboundp 'iterate::sharpL-reader) 1 0)")) (t (c) (list :ERR c))))
(say "X.nobang" (handler-case (eval (read-from-string "(funcall (function iterate::sharpL-reader) (make-string-input-stream \"(list 1)\") #\\L nil)")) (t (c) (list :ERR c))))
(say "X.bang"   (handler-case (eval (read-from-string "(funcall (function iterate::sharpL-reader) (make-string-input-stream \"(list iterate::!1)\") #\\L nil)")) (t (c) (list :ERR c))))
(say "END" "ok")
