(defun say (k v) (princ (concatenate (quote string) k "=" (princ-to-string v))) (terpri) (finish-output))
(defun ldf (path pkgname)
  (let ((p *package*) (r nil))
    (setq *package* (find-package pkgname))
    (setq r (handler-case (%it-eval-source (tar-bytes-to-string (%it-slurp-bytes path)) path)
              (t (c) (list :ERR c))))
    (setq *package* p) r))
(say "L1" (ldf "/home/claude/ws-iter/esc2/itpkg.lisp" "COMMON-LISP-USER"))
(say "L2" (ldf "/home/claude/ws-iter/esc2/fwdmod.lisp" "ITERATE"))
(say "R1" (handler-case (eval (read-from-string "(iterate::ka1 (list 1 2))")) (t (c) (list :ERR c))))
(say "END" "ok")
