(defun say (k v) (princ (concatenate (quote string) k "=" (princ-to-string v))) (terpri) (finish-output))
(defun hx (n) (format nil "~X" n))
(defun fslots ()
  (list :rip (hx (mem-ref #x10000C30 :u64))
        :rsp (hx (mem-ref #x10000C38 :u64))
        :site (hx (mem-ref #x10000C40 :u64))
        :rax (hx (mem-ref #x10000C48 :u64))
        :addr (hx (mem-ref #x10000C50 :u64))))
(defun fclear ()
  (setf (mem-ref #x10000C30 :u64) 0)
  (setf (mem-ref #x10000C38 :u64) 0)
  (setf (mem-ref #x10000C40 :u64) 0)
  (setf (mem-ref #x10000C48 :u64) 0)
  (setf (mem-ref #x10000C50 :u64) 0)
  0)
(defun probe (name src)
  (fclear)
  (say name (handler-case (eval (read-from-string src))
              (t (c) (list :ERR (handler-case (type-of c) (t (c2) :UNK))))))
  (say (concatenate (quote string) name ".fault") (fslots)))
(defun ld (path pkgname)
  (let ((p *package*) (r nil))
    (setq *package* (find-package pkgname))
    (setq r (handler-case (%it-eval-source (tar-bytes-to-string (%it-slurp-bytes path)) path)
              (t (c) (list :ERR (handler-case (type-of c) (t (c2) :UNK))))))
    (setq *package* p) r))
(say "PHASE" "start")
(say "FSLOTS0" (fslots))
(say "LOADPKG" (ld "/home/claude/ws-iter/esc2/package.lisp" "COMMON-LISP-USER"))
(say "PKG" (if (find-package "ITERATE") 1 0))
(say "LOADSHARPL" (ld "/home/claude/ws-iter/esc2/sharpl.lisp" "ITERATE"))
(probe "A.no-bang" "(funcall (function iterate::sharpL-reader) (make-string-input-stream \"(list 1)\") #\\L nil)")
(probe "B.bang" "(funcall (function iterate::sharpL-reader) (make-string-input-stream \"(list iterate::!1)\") #\\L nil)")
(say "END" "ok")
