(setf *load-verbose* nil *compile-verbose* nil)
(format t "~&SBCL ~a on ~a ~a~%" (lisp-implementation-version) (machine-type) (machine-version))
(defvar *t0* (get-internal-real-time))
(handler-bind ((warning #'muffle-warning))
  (dolist (f '("packages" "decode/tables" "decode/bool" "decode/transform" "decode/intra" "decode/loopfilter" "decode/inter-tables" "decode/inter"))
    (load (concatenate 'string "/reel/" f ".lisp"))))
(format t "reel loaded+compiled in ~a ms~%" (round (* 1000 (- (get-internal-real-time) *t0*)) internal-time-units-per-second))
(defun rfb (path) (with-open-file (s path :element-type '(unsigned-byte 8))
  (let* ((n (file-length s)) (v (make-array n :element-type '(unsigned-byte 8)))) (read-sequence v s) v)))
(defun le32 (v o) (logior (aref v o) (ash (aref v (+ o 1)) 8) (ash (aref v (+ o 2)) 16) (ash (aref v (+ o 3)) 24)))
(defun decode-all (ivf) (let ((vd (reel:make-decoder)) (off 32) (n 0)) (loop (when (>= (+ off 12) (length ivf)) (return)) (let* ((sz (le32 ivf off)) (s (+ off 12)) (e (+ s sz))) (reel:decode-frame vd ivf :start s :end e) (setq off e) (incf n))) n))
(dolist (clip '("/reel/cam.ivf" "/reel/vp8-std.ivf"))
  (let ((ivf (rfb clip)))
    (decode-all ivf)
    (let ((t1 (get-internal-real-time)) (n 0))
      (dotimes (k 5) (setq n (decode-all ivf)))
      (let ((ms (/ (* 1000.0 (- (get-internal-real-time) t1)) internal-time-units-per-second)))
        (format t "BENCH ~a: ~a frames x5 in ~,0f ms => ~,2f ms/frame (~,1f fps)~%" clip n ms (/ ms (* 5 n)) (/ (* 5 n 1000) ms))))))
(format t "BENCH DONE~%")
(finish-output)
