(setq *jit-hot-only* nil)
(defvar *dir* "/reel/")
(dolist (f '("packages" "decode/tables" "decode/bool" "decode/transform" "decode/intra" "decode/loopfilter" "decode/inter-tables" "decode/inter"))
  (load (concatenate 'string *dir* f ".lisp")))
(load "/reel/decode/intra-neon.lisp")
(load "/reel/decode/inter-neon.lisp")
(load "/reel/decode/loopfilter-neon.lisp")
(format t "eager=~a~%" (jit-eager))
(defun rfb (path) (with-open-file (s path :element-type '(unsigned-byte 8))
  (let* ((n (file-length s)) (v (make-array n :element-type '(unsigned-byte 8)))) (dotimes (i n) (setf (aref v i) (read-byte s))) v)))
(defun le32 (v o) (logior (aref v o) (ash (aref v (+ o 1)) 8) (ash (aref v (+ o 2)) 16) (ash (aref v (+ o 3)) 24)))
(defun decode-all (ivf) (let ((vd (reel:make-decoder)) (off 32) (n 0)) (loop (when (>= (+ off 12) (length ivf)) (return)) (let* ((sz (le32 ivf off)) (s (+ off 12)) (e (+ s sz))) (reel:decode-frame vd ivf :start s :end e) (setq off e) (incf n))) n))
(dolist (clip '("/reel/vp8-std.ivf" "/reel/cam.ivf"))
  (let* ((t0 (get-internal-real-time)) (ivf (rfb clip)) (tr (- (get-internal-real-time) t0)))
    (decode-all ivf)
    (let ((t1 (get-internal-real-time)) (n 0))
      (dotimes (k 3) (setq n (decode-all ivf)))
      (let ((dt (- (get-internal-real-time) t1)))
        (format t "~a: units ~a read-us ~a n ~a decode-us(x3) ~a => ~a us/frame; pic-y0 ~a~%" clip internal-time-units-per-second tr n dt (round dt (* 3 (max n 1))) (let ((vd (reel:make-decoder)) (sz (le32 ivf 32))) (aref (reel.decode::picture-y (reel:decode-frame vd ivf :start 44 :end (+ 44 sz))) 1000)))))))
