;;; modus-pmu-phases.lisp — per-phase A53 PMU counters from inside hosted Modus (Linux on the Zero).
;;; Same 13 phase wrappers as docs/reel-on-zero/serial-prof.py, but each wrapper accumulates the DELTA of
;;; one perf counter set (bundle 7: cycles, inst, L1I refill, L1D refill, br mispred, L2 refill) per phase.
;;; Wrapper cost: 2 read(2) per counter per call (~1 us each); residue is the most-called phase (~22k calls/pass).
(load "/reel/modus-pmu.lisp")
(defvar *dir* "/reel/")
(dolist (f '("packages" "decode/tables" "decode/bool" "decode/transform" "decode/intra" "decode/loopfilter" "decode/inter-tables" "decode/inter"))
  (load (concatenate 'string *dir* f ".lisp")))
(load "/reel/decode/intra-neon.lisp") (load "/reel/decode/inter-neon.lisp") (load "/reel/decode/loopfilter-neon.lisp")
(defvar *events* (list #x11 #x08 #x01 #x03 #x10 #x17))
(defvar *nev* 6)
(defvar *phases* nil)                      ; list of (name . u64-accumulator-vector)
(defun %pmu-snap (into)
  (let ((i 0)) (dolist (fd *pmu-fds*) (setf (aref into i) (pmu-read fd)) (incf i))))
(defvar *snap-a* (make-array 6 :initial-element 0))
(defvar *snap-b* (make-array 6 :initial-element 0))
(defvar *depth* 0)
(defmacro defphase (name fn args)
  "Wrap FN: snapshot counters on entry into a per-phase preallocated array, add deltas on exit. No per-call allocation
   (the Zero has 415 MB; a GC that touches the second semispace gets Modus OOM-killed). Nested phases are inclusive."
  (let ((o (intern (format nil "*O-~a*" name))) (acc (intern (format nil "*A-~a*" name))) (snap (intern (format nil "*S-~a*" name))))
    `(progn
       (defvar ,o (symbol-function ',fn))
       (defvar ,acc (make-array 6 :initial-element 0))
       (defvar ,snap (make-array 6 :initial-element 0))
       (push (cons ',name ,acc) *phases*)
       (defun ,fn ,args
         (%pmu-snap ,snap)
         (multiple-value-prog1 (funcall ,o ,@args)
           (%pmu-snap *snap-b*)
           (dotimes (i 6) (setf (aref ,acc i) (+ (aref ,acc i) (- (aref *snap-b* i) (aref ,snap i))))))))))
(defphase residue    reel.decode::decode-residue (d bd mbx skip has-y2 dq))
(defphase luma16     reel.decode::reconstruct-luma16 (d mx my ymode ha hl))
(defphase bpred      reel.decode::reconstruct-bpred (d mx my))
(defphase chroma     reel.decode::reconstruct-chroma (d mbx mby uvmode ha hl))
(defphase interpred  reel.decode::predict-inter-mb (vd mi mbx mby mode))
(defphase interres   reel.decode::add-inter-residual (d mx my cx cy))
(defphase mbmodes    reel.decode::read-mb-modes (d part0 mbx))
(defphase intermodes reel.decode::read-inter-modes (vd part0 mi mbx mby))
(defphase intramodes reel.decode::read-intra-modes-inter-frame (vd part0))
(defphase lfparams   reel.decode::mb-filter-params (vd d mi key))
(defphase loopf      reel.decode::loop-filter-frame (vd key))
(defphase refcopy    reel.decode::plane->rframe-plane (pl dst stride border w h))
(defphase mbloop     reel.decode::decode-macroblocks (vd part0 tokens nparts key))
(format t "eager=~a~%" (jit-eager))
(defun rfb (path) (with-open-file (s path :element-type '(unsigned-byte 8))
  (let* ((n (file-length s)) (v (make-array n :element-type '(unsigned-byte 8)))) (dotimes (i n) (setf (aref v i) (read-byte s))) v)))
(defun le32 (v o) (logior (aref v o) (ash (aref v (+ o 1)) 8) (ash (aref v (+ o 2)) 16) (ash (aref v (+ o 3)) 24)))
(defun decode-all (ivf) (let ((vd (reel:make-decoder)) (off 32) (n 0)) (loop (when (>= (+ off 12) (length ivf)) (return)) (let* ((sz (le32 ivf off)) (s (+ off 12)) (e (+ s sz))) (reel:decode-frame vd ivf :start s :end e) (setq off e) (incf n))) n))
(let ((ivf (rfb "/reel/cam.ivf")))
  (pmu-start *events*)
  (%pmu-snap *snap-a*)
  (let ((n (decode-all ivf)))
    (%pmu-snap *snap-b*)
    (pmu-stop)
    (format t "PMU-PHASES frames=~a total cycles/frame=~a inst/frame=~a~%" n
            (round (- (aref *snap-b* 0) (aref *snap-a* 0)) n) (round (- (aref *snap-b* 1) (aref *snap-a* 1)) n))
    (format t "~12a ~9a ~9a ~6a ~7a ~7a ~7a ~7a~%" "phase" "kcyc/fr" "kinst/fr" "IPC" "L1I/ki" "L1D/ki" "brm/ki" "L2/ki")
    (dolist (p (reverse *phases*))
      (let ((a (cdr p)))
        (format t "~12a ~9a ~9a ~6,2f ~7,2f ~7,2f ~7,2f ~7,2f~%" (car p)
                (round (aref a 0) (* 1000 n)) (round (aref a 1) (* 1000 n))
                (/ (aref a 1) (max 1 (aref a 0)))
                (/ (* 1000.0 (aref a 2)) (max 1 (aref a 1))) (/ (* 1000.0 (aref a 3)) (max 1 (aref a 1)))
                (/ (* 1000.0 (aref a 4)) (max 1 (aref a 1))) (/ (* 1000.0 (aref a 5)) (max 1 (aref a 1))))))))
(format t "PMU-PHASES DONE~%")
