(load "/home/modus/modus-pmu.lisp")
(defun f2 (a b) (values (+ a b) (- a b)))
(defun f1 (a b) (+ a b))
(setf (symbol-function (quote orig-f2)) (symbol-function (quote f2)))
(setf (symbol-function (quote orig-f1)) (symbol-function (quote f1)))
(defvar *acc* (make-array 6 :initial-element 0))
(defun w-mvp1 (a b) (multiple-value-prog1 (orig-f2 a b) (setf (aref *acc* 0) (+ (aref *acc* 0) 1))))
(defun w-prog1 (a b) (prog1 (orig-f1 a b) (setf (aref *acc* 0) (+ (aref *acc* 0) 1))))
(defun w-mvp1-nobody (a b) (multiple-value-prog1 (orig-f2 a b)))
(defun w-mvlist (a b) (let ((r (orig-f2 a b))) (setf (aref *acc* 0) (+ (aref *acc* 0) 1)) r))
(defun w-dotimes (a b) (prog1 (orig-f1 a b) (dotimes (i 6) (setf (aref *acc* i) (+ (aref *acc* i) (- (aref *acc* i) (aref *acc* i)))))))
(defun run (fn n) (let ((s 0)) (dotimes (i n) (setq s (+ s (funcall fn i 1)))) s))
(defun run-direct-f2 (n) (let ((s 0)) (dotimes (i n) (setq s (+ s (f2 i 1)))) s))
(defun run-direct-w-mvp1 (n) (let ((s 0)) (dotimes (i n) (setq s (+ s (w-mvp1 i 1)))) s))
(defun run-direct-w-prog1 (n) (let ((s 0)) (dotimes (i n) (setq s (+ s (w-prog1 i 1)))) s))
(defun run-direct-w-mvp1-nobody (n) (let ((s 0)) (dotimes (i n) (setq s (+ s (w-mvp1-nobody i 1)))) s))
(defun run-direct-w-mvlist (n) (let ((s 0)) (dotimes (i n) (setq s (+ s (w-mvlist i 1)))) s))
(defun run-direct-w-dotimes (n) (let ((s 0)) (dotimes (i n) (setq s (+ s (w-dotimes i 1)))) s))
(format t "eager=~a~%" (jit-eager))
(dolist (r (list (quote run-direct-f2) (quote run-direct-w-mvp1) (quote run-direct-w-prog1) (quote run-direct-w-mvp1-nobody) (quote run-direct-w-mvlist) (quote run-direct-w-dotimes)))
  (funcall r 1000)
  (pmu-start (list #x11 #x08))
  (funcall r 100000)
  (let ((v (pmu-stop))) (format t "~28a inst/call=~a cyc/call=~a~%" r (round (second v) 100000) (round (first v) 100000))))
(finish-output)
