(load "/home/modus/modus-pmu.lisp")
(defun f1 (a b) (+ a b))
(setf (symbol-function (quote orig-f1)) (symbol-function (quote f1)))
(defvar *acc* (make-array 6 :element-type (quote (signed-byte 32)) :initial-element 0))
(defvar *snap* (make-array 6 :element-type (quote (signed-byte 32)) :initial-element 0))
(defun w-dotimes-generic (a b) (prog1 (orig-f1 a b) (dotimes (i 6) (setf (aref *acc* i) (+ (aref *acc* i) (- (aref *snap* i) (aref *acc* i)))))))
(defun w-dotimes-typed (a b)
  (let ((acc *acc*) (snap *snap*))
    (declare (type (simple-array (signed-byte 32) (*)) acc snap) (optimize (speed 3) (safety 0)))
    (prog1 (orig-f1 a b) (dotimes (i 6) (declare (type fixnum i)) (setf (aref acc i) (+ (aref acc i) (- (aref snap i) (aref acc i))))))))
(defun snap-typed (into)
  (declare (type (simple-array (signed-byte 32) (*)) into) (optimize (speed 3) (safety 0)))
  (syscall3 0 (car *pmu-fds*) *io-buf-addr* 56)
  (dotimes (i 6) (declare (type fixnum i)) (setf (aref into i) (%u64-at (+ *io-buf-addr* 8 (* 8 i))))))
(defun w-snap (a b) (snap-typed *snap*) (prog1 (orig-f1 a b) (snap-typed *snap*)))
(defun w-nosys (a b) (dotimes (i 6) (declare (type fixnum i)) (setf (aref *snap* i) (%u64-at (+ *io-buf-addr* 8 (* 8 i))))) (orig-f1 a b))
(defun run-g (n) (let ((s 0)) (dotimes (i n) (setq s (+ s (w-dotimes-generic i 1)))) s))
(defun run-t (n) (let ((s 0)) (dotimes (i n) (setq s (+ s (w-dotimes-typed i 1)))) s))
(defun run-s (n) (let ((s 0)) (dotimes (i n) (setq s (+ s (w-snap i 1)))) s))
(defun run-n (n) (let ((s 0)) (dotimes (i n) (setq s (+ s (w-nosys i 1)))) s))
(format t "eager=~a~%" (jit-eager))
(dolist (r (list (quote run-g) (quote run-t) (quote run-n) (quote run-s)))
  (funcall r 1000)
  (pmu-start (list #x11 #x08))
  (funcall r 100000)
  (let ((v (pmu-stop))) (format t "~10a inst/call=~a cyc/call=~a  acc0=~a~%" r (round (second v) 100000) (round (first v) 100000) (aref *acc* 0))))
(finish-output)
