;;;; snp-ghcb.lisp -- the guest side of the GHCB protocol (x86-64 UEFI CL image).
;;;;
;;;; Under SEV-SNP the guest's state is encrypted, so the hypervisor cannot
;;;; decode a trapped instruction for it.  Anything that needs the hypervisor --
;;;; a guest request to the PSP, or an access to an emulated device's MMIO
;;;; registers -- is asked for explicitly: fill the GHCB (a page in shared, C=0
;;;; memory), mark the fields valid, and VMGEXIT.  The boot stub
;;;; (boot/boot-uefi-snp.lisp) keeps a status block at 0x1A000 (one page, below
;;;; the #VC handler's, outside every image):
;;;;   +0x00 u32  1 if SNP is active (C-bit found, shared region + GHCB set up)
;;;;   +0x28 u64  GPA of the SNP secrets page (from the EFI CC-blob table), or 0
;;;;   +0x30 u64  a TAGGED function pointer to the VMGEXIT routine (addr | 3)
;;;;   +0x38 u64  GPA of the GHCB
;;;;   +0x40 u64  base of the 2 MB shared (C=0) region
;;;; Attestation (net/snp-attest.lisp) and the virtio NIC (net/virtio-net.lisp)
;;;; both sit on this file.
;;;;
;;;; %SNP-BUILD-MODE is generated by the build: 0 plain, 1 :snp, 2 :test.  Only
;;;; an SNP-mode stub writes the status block, and bare-metal memory is not
;;;; zeroed, so a plain image must never read it: every predicate here asks the
;;;; build mode first.

(defconstant +snp-w-base+    #x1A000)   ; = boot-uefi-snp.lisp's +snp-status-base+
(defconstant +snp-w-active+  #x1A000)
(defconstant +snp-w-vmgexit+ #x1A030)
(defconstant +snp-w-ghcb+    #x1A038)
(defconstant +snp-w-shared+  #x1A040)

;; GHCB fields (GHCB spec 2.0): sw_exit_code, sw_exit_info_1/2, sw_scratch, the
;; valid bitmap, and the shared buffer the scratch field may point into.
(defconstant +ghcb-exit-code+  #x390)
(defconstant +ghcb-exit-info1+ #x398)
(defconstant +ghcb-exit-info2+ #x3A0)
(defconstant +ghcb-scratch+    #x3A8)
(defconstant +ghcb-valid+      #x3F0)
(defconstant +ghcb-buffer+     #x800)

(defconstant +svm-vmgexit-mmio-read+  #x80000001)
(defconstant +svm-vmgexit-mmio-write+ #x80000002)

;; A :u64 mem-ref hands back the RAW word as a Lisp value (a GPA with bit 0
;; clear reads as the fixnum GPA/2), so addresses are read as two :u32 halves.
(defun %snp-u64v (a) (+ (mem-ref a :u32) (ash (mem-ref (+ a 4) :u32) 32)))
(defun snp-active-p ()
  (and (= (%snp-build-mode) 1) (= (mem-ref +snp-w-active+ :u32) 1)))
(defun snp-ghcb-gpa () (%snp-u64v +snp-w-ghcb+))
(defun snp-shared-base () (%snp-u64v +snp-w-shared+))
(defun snp-vmgexit-word-p () (= (logand (mem-ref +snp-w-vmgexit+ :u32) 15) 3))
(defun snp-vmgexit ()
  "REP VMMCALL through the stub's routine.  The word IS a tagged fn pointer, so
   reading it raw and FUNCALLing it is the ordinary indirect call (sub 3; call).
   In :TEST mode the routine is `mov eax,NIL; ret' -- callable on any machine."
  (funcall (mem-ref +snp-w-vmgexit+ :u64)))

(defun %snp-zero (addr n) (dotimes (i n) (setf (mem-ref (+ addr i) :u8) 0)))

(defun %ghcb-put-u64 (g off val)
  (setf (mem-ref (+ g off) :u32) (logand val #xFFFFFFFF))
  (setf (mem-ref (+ g off 4) :u32) (logand (ash val -32) #xFFFFFFFF)))
(defun %ghcb-set-valid (g field)
  ;; valid bitmap at 0x3F0: bit (field/8) -- byte (field/8)/8, bit (field/8)%8
  (let* ((idx (floor field 8)) (a (+ g +ghcb-valid+ (floor idx 8))))
    (setf (mem-ref a :u8) (logior (mem-ref a :u8) (ash 1 (mod idx 8))))))
(defun %ghcb-put (g field val)
  (%ghcb-put-u64 g field val)
  (%ghcb-set-valid g field))
(defun %ghcb-begin (g)
  "Clear the valid bitmap and stamp usage 0 (GHCB) / protocol version 2."
  (%snp-zero (+ g +ghcb-valid+) 16)
  (setf (mem-ref (+ g #xFFC) :u32) 0)
  (setf (mem-ref (+ g #xFFA) :u8) 2)
  (setf (mem-ref (+ g #xFFB) :u8) 0))

;; ------------------------------------------------------------------
;; Device MMIO.
;;
;; A plain load or store to an emulated device's registers is a nested page
;; fault the hypervisor cannot service for an SNP guest: it arrives as #VC,
;; and the stub's handler covers port I/O, CPUID, MSRs and RDTSC only.  So
;; under SNP a driver does not touch the registers at all; it asks.  MMIO
;; read/write NAE: sw_exit_info_1 = the register's GPA, sw_exit_info_2 = the
;; access size in bytes, sw_scratch = the GHCB's own shared buffer, which
;; carries the data.  sw_exit_info_1 comes back 0 on success.
;;
;; In :TEST mode there is no hypervisor and the VMGEXIT routine is a no-op, so
;; %SNP-TEST-MMIO plays the hypervisor's part from the GHCB fields -- the same
;; arrangement the stub's #VC handler uses to emulate port I/O on a plain
;; machine.  That runs every byte of the guest's side of the protocol.
;; ------------------------------------------------------------------
(defun snp-mmio-real-p () (snp-active-p))
(defun snp-mmio-p () (or (= (%snp-build-mode) 2) (snp-mmio-real-p)))

(defun %snp-mem-get (addr size)
  (cond ((= size 1) (mem-ref addr :u8))
        ((= size 2) (mem-ref addr :u16))
        (t (mem-ref addr :u32))))
(defun %snp-mem-put (addr size v)
  (cond ((= size 1) (setf (mem-ref addr :u8) v))
        ((= size 2) (setf (mem-ref addr :u16) v))
        (t (setf (mem-ref addr :u32) v))))

(defun %snp-test-mmio (g)
  "The hypervisor's half of an MMIO exit, for :TEST builds only."
  (let ((code (%snp-u64v (+ g +ghcb-exit-code+)))
        (gpa  (%snp-u64v (+ g +ghcb-exit-info1+)))
        (size (%snp-u64v (+ g +ghcb-exit-info2+)))
        (buf  (%snp-u64v (+ g +ghcb-scratch+))))
    (if (= code +svm-vmgexit-mmio-read+)
        (%snp-mem-put buf size (%snp-mem-get gpa size))
        (%snp-mem-put gpa size (%snp-mem-get buf size)))
    (%ghcb-put-u64 g +ghcb-exit-info1+ 0)))

(defun %snp-mmio-exit (code gpa size)
  "One MMIO NAE; the data is at the GHCB buffer.  -> sw_exit_info_1's low word."
  (let ((g (snp-ghcb-gpa)))
    (%ghcb-put g +ghcb-exit-code+ code)
    (%ghcb-put g +ghcb-exit-info1+ gpa)
    (%ghcb-put g +ghcb-exit-info2+ size)
    (%ghcb-put g +ghcb-scratch+ (+ g +ghcb-buffer+))
    (snp-vmgexit)
    (when (= (%snp-build-mode) 2) (%snp-test-mmio g))
    (let ((st (logand (%snp-u64v (+ g +ghcb-exit-info1+)) #xFFFFFFFF)))
      (when (not (zerop st))
        (write-string-serial "SNP:MMIO-ERR ") (print-hex32 code)
        (write-char-serial 32) (print-hex32 (logand gpa #xFFFFFFFF))
        (write-char-serial 10))
      st)))

(defun snp-mmio-read (gpa size)
  "Read SIZE (1, 2 or 4) bytes of device register GPA through the hypervisor."
  (let ((g (snp-ghcb-gpa)))
    (%ghcb-begin g)
    (%snp-mem-put (+ g +ghcb-buffer+) 4 0)
    (%snp-mmio-exit +svm-vmgexit-mmio-read+ gpa size)
    (%snp-mem-get (+ g +ghcb-buffer+) size)))

(defun snp-mmio-write (gpa size v)
  "Write V as SIZE (1, 2 or 4) bytes to device register GPA through the hypervisor."
  (let ((g (snp-ghcb-gpa)))
    (%ghcb-begin g)
    (%snp-mem-put (+ g +ghcb-buffer+) size v)
    (%snp-mmio-exit +svm-vmgexit-mmio-write+ gpa size)
    v))
