#!/usr/bin/env bash
# deploy-pages.sh — publish the browser REPL to an orphan `gh-pages` branch
# that GitHub Pages can serve.  Run from anywhere in the repo.
#
#   web/deploy-pages.sh [remote] [branch]      # defaults: origin gh-pages
#
# GitHub Pages cannot send COOP/COEP, so coi-serviceworker.js supplies them
# (see index.html).  Only the browser-side files and the two gzipped
# artifacts are published; the node host and tests are not.
set -euo pipefail
here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(git -C "$here" rev-parse --show-toplevel)"
remote="${1:-origin}"
branch="${2:-gh-pages}"

cd "$here"
[ -f modus.mvmw ] || { echo "modus.mvmw missing — build it: MODUS_NO_JIT=1 sbcl --dynamic-space-size 8192 --script mvm/build-web.lisp" >&2; exit 1; }
[ -f modus.core.gz ] || { echo "modus.core.gz missing — make it: node web/run-node.js --trace 1 --save-core web/modus.core.gz --eval '(print 1)' --quit" >&2; exit 1; }
gzip -9 -k -f modus.mvmw            # refresh modus.mvmw.gz from the current module

files=(index.html coi-serviceworker.js mvm.js host-browser.js worker.js warmset.js modus.mvmw.gz modus.core.gz)
for f in "${files[@]}"; do [ -f "$f" ] || { echo "missing $f" >&2; exit 1; }; done

tmp="$(mktemp -d)"
cleanup() { git -C "$root" worktree remove --force "$tmp" 2>/dev/null || true; }
trap cleanup EXIT
git -C "$root" worktree add --detach "$tmp" >/dev/null
cd "$tmp"
git checkout --orphan "$branch" >/dev/null 2>&1
git rm -rf --quiet . >/dev/null 2>&1 || true
find . -maxdepth 1 -mindepth 1 ! -name .git -exec rm -rf {} +
for f in "${files[@]}"; do cp "$here/$f" .; done
mkdir -p samples; cp "$here"/samples/*.lisp samples/   # sample library for the ▶ samples menu
touch .nojekyll
cat > README.md <<'MD'
# Modus REPL (GitHub Pages)

This branch is the deployable browser REPL. Enable it under
**Settings → Pages → Deploy from a branch → `gh-pages` / (root)**.

It is generated by `web/deploy-pages.sh` from the `web-interp` branch; edit
sources there, not here. `coi-serviceworker.js` provides the cross-origin
isolation SharedArrayBuffer needs, which GitHub Pages cannot set via headers.
MD
git add -A
git commit -q -m "Deploy browser REPL to GitHub Pages ($(date -u +%Y-%m-%dT%H:%MZ))"
git push -f "$remote" "$branch"
echo "pushed $branch to $remote"
